// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: message.proto
//
package com.common

import com.connectrpc.BidirectionalStreamInterface
import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.StreamType

/**
 *  使用 stream 发送、接收消息
 */
public class StreamMessageServiceClient(
  private val client: ProtocolClientInterface,
) : StreamMessageServiceClientInterface {
  override suspend fun streamChatMessage(headers: Headers): BidirectionalStreamInterface<StreamChatMessageRequest, StreamChatMessageResponse> = client.stream(
    headers,
    MethodSpec(
    "common.StreamMessageService/StreamChatMessage",
      com.common.StreamChatMessageRequest::class,
      com.common.StreamChatMessageResponse::class,
      StreamType.BIDI,
    ),
  )

}
