// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: error.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * <pre>
 * 认证和授权错误描述
 * </pre>
 *
 * Protobuf type {@code rankquantity.voyager.api.AuthErrorMessages}
 */
@com.google.protobuf.Generated
public final class AuthErrorMessages extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.AuthErrorMessages)
    AuthErrorMessagesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      AuthErrorMessages.class.getName());
  }
  // Use AuthErrorMessages.newBuilder() to construct.
  private AuthErrorMessages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuthErrorMessages() {
    uNAUTHORIZED_ = "";
    tOKENEXPIRED_ = "";
    tOKENINVALID_ = "";
    pERMISSIONDENIED_ = "";
    aCCOUNTNOTFOUND_ = "";
    wRONGPASSWORD_ = "";
    aCCOUNTDISABLED_ = "";
    lOGINREQUIRED_ = "";
    tOKENMISSING_ = "";
    sESSIONEXPIRED_ = "";
    iNVALIDCREDENTIALS_ = "";
    aCCOUNTLOCKED_ = "";
    aCCOUNTEXPIRED_ = "";
    iNVALIDLOGINTYPE_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_AuthErrorMessages_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_AuthErrorMessages_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.AuthErrorMessages.class, com.rankquantity.voyager.api.AuthErrorMessages.Builder.class);
  }

  public static final int UNAUTHORIZED_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uNAUTHORIZED_ = "";
  /**
   * <pre>
   * 未授权
   * </pre>
   *
   * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
   * @return The uNAUTHORIZED.
   */
  @java.lang.Override
  public java.lang.String getUNAUTHORIZED() {
    java.lang.Object ref = uNAUTHORIZED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uNAUTHORIZED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 未授权
   * </pre>
   *
   * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
   * @return The bytes for uNAUTHORIZED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUNAUTHORIZEDBytes() {
    java.lang.Object ref = uNAUTHORIZED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uNAUTHORIZED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_EXPIRED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tOKENEXPIRED_ = "";
  /**
   * <pre>
   * Token过期
   * </pre>
   *
   * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
   * @return The tOKENEXPIRED.
   */
  @java.lang.Override
  public java.lang.String getTOKENEXPIRED() {
    java.lang.Object ref = tOKENEXPIRED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tOKENEXPIRED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Token过期
   * </pre>
   *
   * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
   * @return The bytes for tOKENEXPIRED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTOKENEXPIREDBytes() {
    java.lang.Object ref = tOKENEXPIRED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tOKENEXPIRED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_INVALID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tOKENINVALID_ = "";
  /**
   * <pre>
   * Token无效
   * </pre>
   *
   * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
   * @return The tOKENINVALID.
   */
  @java.lang.Override
  public java.lang.String getTOKENINVALID() {
    java.lang.Object ref = tOKENINVALID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tOKENINVALID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Token无效
   * </pre>
   *
   * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
   * @return The bytes for tOKENINVALID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTOKENINVALIDBytes() {
    java.lang.Object ref = tOKENINVALID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tOKENINVALID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSION_DENIED_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pERMISSIONDENIED_ = "";
  /**
   * <pre>
   * 权限不足
   * </pre>
   *
   * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
   * @return The pERMISSIONDENIED.
   */
  @java.lang.Override
  public java.lang.String getPERMISSIONDENIED() {
    java.lang.Object ref = pERMISSIONDENIED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pERMISSIONDENIED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 权限不足
   * </pre>
   *
   * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
   * @return The bytes for pERMISSIONDENIED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPERMISSIONDENIEDBytes() {
    java.lang.Object ref = pERMISSIONDENIED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pERMISSIONDENIED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_NOT_FOUND_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aCCOUNTNOTFOUND_ = "";
  /**
   * <pre>
   * 账号不存在
   * </pre>
   *
   * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
   * @return The aCCOUNTNOTFOUND.
   */
  @java.lang.Override
  public java.lang.String getACCOUNTNOTFOUND() {
    java.lang.Object ref = aCCOUNTNOTFOUND_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aCCOUNTNOTFOUND_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账号不存在
   * </pre>
   *
   * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
   * @return The bytes for aCCOUNTNOTFOUND.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getACCOUNTNOTFOUNDBytes() {
    java.lang.Object ref = aCCOUNTNOTFOUND_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aCCOUNTNOTFOUND_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WRONG_PASSWORD_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object wRONGPASSWORD_ = "";
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
   * @return The wRONGPASSWORD.
   */
  @java.lang.Override
  public java.lang.String getWRONGPASSWORD() {
    java.lang.Object ref = wRONGPASSWORD_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wRONGPASSWORD_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 密码错误
   * </pre>
   *
   * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
   * @return The bytes for wRONGPASSWORD.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWRONGPASSWORDBytes() {
    java.lang.Object ref = wRONGPASSWORD_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wRONGPASSWORD_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_DISABLED_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aCCOUNTDISABLED_ = "";
  /**
   * <pre>
   * 账号已禁用
   * </pre>
   *
   * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
   * @return The aCCOUNTDISABLED.
   */
  @java.lang.Override
  public java.lang.String getACCOUNTDISABLED() {
    java.lang.Object ref = aCCOUNTDISABLED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aCCOUNTDISABLED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账号已禁用
   * </pre>
   *
   * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
   * @return The bytes for aCCOUNTDISABLED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getACCOUNTDISABLEDBytes() {
    java.lang.Object ref = aCCOUNTDISABLED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aCCOUNTDISABLED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGIN_REQUIRED_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lOGINREQUIRED_ = "";
  /**
   * <pre>
   * 需要登录
   * </pre>
   *
   * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
   * @return The lOGINREQUIRED.
   */
  @java.lang.Override
  public java.lang.String getLOGINREQUIRED() {
    java.lang.Object ref = lOGINREQUIRED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lOGINREQUIRED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 需要登录
   * </pre>
   *
   * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
   * @return The bytes for lOGINREQUIRED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLOGINREQUIREDBytes() {
    java.lang.Object ref = lOGINREQUIRED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lOGINREQUIRED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_MISSING_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tOKENMISSING_ = "";
  /**
   * <pre>
   * Token缺失
   * </pre>
   *
   * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
   * @return The tOKENMISSING.
   */
  @java.lang.Override
  public java.lang.String getTOKENMISSING() {
    java.lang.Object ref = tOKENMISSING_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tOKENMISSING_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Token缺失
   * </pre>
   *
   * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
   * @return The bytes for tOKENMISSING.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTOKENMISSINGBytes() {
    java.lang.Object ref = tOKENMISSING_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tOKENMISSING_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_EXPIRED_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sESSIONEXPIRED_ = "";
  /**
   * <pre>
   * 会话过期
   * </pre>
   *
   * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
   * @return The sESSIONEXPIRED.
   */
  @java.lang.Override
  public java.lang.String getSESSIONEXPIRED() {
    java.lang.Object ref = sESSIONEXPIRED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sESSIONEXPIRED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话过期
   * </pre>
   *
   * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
   * @return The bytes for sESSIONEXPIRED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSESSIONEXPIREDBytes() {
    java.lang.Object ref = sESSIONEXPIRED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sESSIONEXPIRED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVALID_CREDENTIALS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object iNVALIDCREDENTIALS_ = "";
  /**
   * <pre>
   * 无效的凭证
   * </pre>
   *
   * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
   * @return The iNVALIDCREDENTIALS.
   */
  @java.lang.Override
  public java.lang.String getINVALIDCREDENTIALS() {
    java.lang.Object ref = iNVALIDCREDENTIALS_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iNVALIDCREDENTIALS_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 无效的凭证
   * </pre>
   *
   * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
   * @return The bytes for iNVALIDCREDENTIALS.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getINVALIDCREDENTIALSBytes() {
    java.lang.Object ref = iNVALIDCREDENTIALS_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iNVALIDCREDENTIALS_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_LOCKED_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aCCOUNTLOCKED_ = "";
  /**
   * <pre>
   * 账号已锁定
   * </pre>
   *
   * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
   * @return The aCCOUNTLOCKED.
   */
  @java.lang.Override
  public java.lang.String getACCOUNTLOCKED() {
    java.lang.Object ref = aCCOUNTLOCKED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aCCOUNTLOCKED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账号已锁定
   * </pre>
   *
   * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
   * @return The bytes for aCCOUNTLOCKED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getACCOUNTLOCKEDBytes() {
    java.lang.Object ref = aCCOUNTLOCKED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aCCOUNTLOCKED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_EXPIRED_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object aCCOUNTEXPIRED_ = "";
  /**
   * <pre>
   * 账号已过期
   * </pre>
   *
   * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
   * @return The aCCOUNTEXPIRED.
   */
  @java.lang.Override
  public java.lang.String getACCOUNTEXPIRED() {
    java.lang.Object ref = aCCOUNTEXPIRED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aCCOUNTEXPIRED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账号已过期
   * </pre>
   *
   * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
   * @return The bytes for aCCOUNTEXPIRED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getACCOUNTEXPIREDBytes() {
    java.lang.Object ref = aCCOUNTEXPIRED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aCCOUNTEXPIRED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVALID_LOGIN_TYPE_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object iNVALIDLOGINTYPE_ = "";
  /**
   * <pre>
   * 无效的登录类型
   * </pre>
   *
   * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
   * @return The iNVALIDLOGINTYPE.
   */
  @java.lang.Override
  public java.lang.String getINVALIDLOGINTYPE() {
    java.lang.Object ref = iNVALIDLOGINTYPE_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iNVALIDLOGINTYPE_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 无效的登录类型
   * </pre>
   *
   * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
   * @return The bytes for iNVALIDLOGINTYPE.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getINVALIDLOGINTYPEBytes() {
    java.lang.Object ref = iNVALIDLOGINTYPE_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iNVALIDLOGINTYPE_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uNAUTHORIZED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uNAUTHORIZED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENEXPIRED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tOKENEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENINVALID_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tOKENINVALID_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pERMISSIONDENIED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, pERMISSIONDENIED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTNOTFOUND_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, aCCOUNTNOTFOUND_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(wRONGPASSWORD_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, wRONGPASSWORD_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTDISABLED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, aCCOUNTDISABLED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lOGINREQUIRED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, lOGINREQUIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENMISSING_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, tOKENMISSING_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sESSIONEXPIRED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, sESSIONEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iNVALIDCREDENTIALS_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, iNVALIDCREDENTIALS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTLOCKED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, aCCOUNTLOCKED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTEXPIRED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, aCCOUNTEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iNVALIDLOGINTYPE_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 14, iNVALIDLOGINTYPE_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uNAUTHORIZED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uNAUTHORIZED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENEXPIRED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tOKENEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENINVALID_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, tOKENINVALID_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pERMISSIONDENIED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, pERMISSIONDENIED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTNOTFOUND_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, aCCOUNTNOTFOUND_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(wRONGPASSWORD_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, wRONGPASSWORD_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTDISABLED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, aCCOUNTDISABLED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lOGINREQUIRED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, lOGINREQUIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tOKENMISSING_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, tOKENMISSING_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sESSIONEXPIRED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, sESSIONEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iNVALIDCREDENTIALS_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, iNVALIDCREDENTIALS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTLOCKED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, aCCOUNTLOCKED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(aCCOUNTEXPIRED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, aCCOUNTEXPIRED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iNVALIDLOGINTYPE_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(14, iNVALIDLOGINTYPE_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.AuthErrorMessages)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.AuthErrorMessages other = (com.rankquantity.voyager.api.AuthErrorMessages) obj;

    if (!getUNAUTHORIZED()
        .equals(other.getUNAUTHORIZED())) return false;
    if (!getTOKENEXPIRED()
        .equals(other.getTOKENEXPIRED())) return false;
    if (!getTOKENINVALID()
        .equals(other.getTOKENINVALID())) return false;
    if (!getPERMISSIONDENIED()
        .equals(other.getPERMISSIONDENIED())) return false;
    if (!getACCOUNTNOTFOUND()
        .equals(other.getACCOUNTNOTFOUND())) return false;
    if (!getWRONGPASSWORD()
        .equals(other.getWRONGPASSWORD())) return false;
    if (!getACCOUNTDISABLED()
        .equals(other.getACCOUNTDISABLED())) return false;
    if (!getLOGINREQUIRED()
        .equals(other.getLOGINREQUIRED())) return false;
    if (!getTOKENMISSING()
        .equals(other.getTOKENMISSING())) return false;
    if (!getSESSIONEXPIRED()
        .equals(other.getSESSIONEXPIRED())) return false;
    if (!getINVALIDCREDENTIALS()
        .equals(other.getINVALIDCREDENTIALS())) return false;
    if (!getACCOUNTLOCKED()
        .equals(other.getACCOUNTLOCKED())) return false;
    if (!getACCOUNTEXPIRED()
        .equals(other.getACCOUNTEXPIRED())) return false;
    if (!getINVALIDLOGINTYPE()
        .equals(other.getINVALIDLOGINTYPE())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UNAUTHORIZED_FIELD_NUMBER;
    hash = (53 * hash) + getUNAUTHORIZED().hashCode();
    hash = (37 * hash) + TOKEN_EXPIRED_FIELD_NUMBER;
    hash = (53 * hash) + getTOKENEXPIRED().hashCode();
    hash = (37 * hash) + TOKEN_INVALID_FIELD_NUMBER;
    hash = (53 * hash) + getTOKENINVALID().hashCode();
    hash = (37 * hash) + PERMISSION_DENIED_FIELD_NUMBER;
    hash = (53 * hash) + getPERMISSIONDENIED().hashCode();
    hash = (37 * hash) + ACCOUNT_NOT_FOUND_FIELD_NUMBER;
    hash = (53 * hash) + getACCOUNTNOTFOUND().hashCode();
    hash = (37 * hash) + WRONG_PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getWRONGPASSWORD().hashCode();
    hash = (37 * hash) + ACCOUNT_DISABLED_FIELD_NUMBER;
    hash = (53 * hash) + getACCOUNTDISABLED().hashCode();
    hash = (37 * hash) + LOGIN_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + getLOGINREQUIRED().hashCode();
    hash = (37 * hash) + TOKEN_MISSING_FIELD_NUMBER;
    hash = (53 * hash) + getTOKENMISSING().hashCode();
    hash = (37 * hash) + SESSION_EXPIRED_FIELD_NUMBER;
    hash = (53 * hash) + getSESSIONEXPIRED().hashCode();
    hash = (37 * hash) + INVALID_CREDENTIALS_FIELD_NUMBER;
    hash = (53 * hash) + getINVALIDCREDENTIALS().hashCode();
    hash = (37 * hash) + ACCOUNT_LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + getACCOUNTLOCKED().hashCode();
    hash = (37 * hash) + ACCOUNT_EXPIRED_FIELD_NUMBER;
    hash = (53 * hash) + getACCOUNTEXPIRED().hashCode();
    hash = (37 * hash) + INVALID_LOGIN_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getINVALIDLOGINTYPE().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.AuthErrorMessages parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.AuthErrorMessages parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.AuthErrorMessages parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.AuthErrorMessages prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 认证和授权错误描述
   * </pre>
   *
   * Protobuf type {@code rankquantity.voyager.api.AuthErrorMessages}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.AuthErrorMessages)
      com.rankquantity.voyager.api.AuthErrorMessagesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_AuthErrorMessages_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_AuthErrorMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.AuthErrorMessages.class, com.rankquantity.voyager.api.AuthErrorMessages.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.AuthErrorMessages.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uNAUTHORIZED_ = "";
      tOKENEXPIRED_ = "";
      tOKENINVALID_ = "";
      pERMISSIONDENIED_ = "";
      aCCOUNTNOTFOUND_ = "";
      wRONGPASSWORD_ = "";
      aCCOUNTDISABLED_ = "";
      lOGINREQUIRED_ = "";
      tOKENMISSING_ = "";
      sESSIONEXPIRED_ = "";
      iNVALIDCREDENTIALS_ = "";
      aCCOUNTLOCKED_ = "";
      aCCOUNTEXPIRED_ = "";
      iNVALIDLOGINTYPE_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_AuthErrorMessages_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.AuthErrorMessages getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.AuthErrorMessages.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.AuthErrorMessages build() {
      com.rankquantity.voyager.api.AuthErrorMessages result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.AuthErrorMessages buildPartial() {
      com.rankquantity.voyager.api.AuthErrorMessages result = new com.rankquantity.voyager.api.AuthErrorMessages(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.AuthErrorMessages result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uNAUTHORIZED_ = uNAUTHORIZED_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tOKENEXPIRED_ = tOKENEXPIRED_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tOKENINVALID_ = tOKENINVALID_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pERMISSIONDENIED_ = pERMISSIONDENIED_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.aCCOUNTNOTFOUND_ = aCCOUNTNOTFOUND_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.wRONGPASSWORD_ = wRONGPASSWORD_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.aCCOUNTDISABLED_ = aCCOUNTDISABLED_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.lOGINREQUIRED_ = lOGINREQUIRED_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.tOKENMISSING_ = tOKENMISSING_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.sESSIONEXPIRED_ = sESSIONEXPIRED_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.iNVALIDCREDENTIALS_ = iNVALIDCREDENTIALS_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.aCCOUNTLOCKED_ = aCCOUNTLOCKED_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.aCCOUNTEXPIRED_ = aCCOUNTEXPIRED_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.iNVALIDLOGINTYPE_ = iNVALIDLOGINTYPE_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.AuthErrorMessages) {
        return mergeFrom((com.rankquantity.voyager.api.AuthErrorMessages)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.AuthErrorMessages other) {
      if (other == com.rankquantity.voyager.api.AuthErrorMessages.getDefaultInstance()) return this;
      if (!other.getUNAUTHORIZED().isEmpty()) {
        uNAUTHORIZED_ = other.uNAUTHORIZED_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTOKENEXPIRED().isEmpty()) {
        tOKENEXPIRED_ = other.tOKENEXPIRED_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTOKENINVALID().isEmpty()) {
        tOKENINVALID_ = other.tOKENINVALID_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPERMISSIONDENIED().isEmpty()) {
        pERMISSIONDENIED_ = other.pERMISSIONDENIED_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getACCOUNTNOTFOUND().isEmpty()) {
        aCCOUNTNOTFOUND_ = other.aCCOUNTNOTFOUND_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getWRONGPASSWORD().isEmpty()) {
        wRONGPASSWORD_ = other.wRONGPASSWORD_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getACCOUNTDISABLED().isEmpty()) {
        aCCOUNTDISABLED_ = other.aCCOUNTDISABLED_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getLOGINREQUIRED().isEmpty()) {
        lOGINREQUIRED_ = other.lOGINREQUIRED_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getTOKENMISSING().isEmpty()) {
        tOKENMISSING_ = other.tOKENMISSING_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getSESSIONEXPIRED().isEmpty()) {
        sESSIONEXPIRED_ = other.sESSIONEXPIRED_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getINVALIDCREDENTIALS().isEmpty()) {
        iNVALIDCREDENTIALS_ = other.iNVALIDCREDENTIALS_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getACCOUNTLOCKED().isEmpty()) {
        aCCOUNTLOCKED_ = other.aCCOUNTLOCKED_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getACCOUNTEXPIRED().isEmpty()) {
        aCCOUNTEXPIRED_ = other.aCCOUNTEXPIRED_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getINVALIDLOGINTYPE().isEmpty()) {
        iNVALIDLOGINTYPE_ = other.iNVALIDLOGINTYPE_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uNAUTHORIZED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              tOKENEXPIRED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tOKENINVALID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              pERMISSIONDENIED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              aCCOUNTNOTFOUND_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              wRONGPASSWORD_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              aCCOUNTDISABLED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              lOGINREQUIRED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              tOKENMISSING_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              sESSIONEXPIRED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              iNVALIDCREDENTIALS_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              aCCOUNTLOCKED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              aCCOUNTEXPIRED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              iNVALIDLOGINTYPE_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object uNAUTHORIZED_ = "";
    /**
     * <pre>
     * 未授权
     * </pre>
     *
     * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
     * @return The uNAUTHORIZED.
     */
    public java.lang.String getUNAUTHORIZED() {
      java.lang.Object ref = uNAUTHORIZED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uNAUTHORIZED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 未授权
     * </pre>
     *
     * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
     * @return The bytes for uNAUTHORIZED.
     */
    public com.google.protobuf.ByteString
        getUNAUTHORIZEDBytes() {
      java.lang.Object ref = uNAUTHORIZED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uNAUTHORIZED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 未授权
     * </pre>
     *
     * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
     * @param value The uNAUTHORIZED to set.
     * @return This builder for chaining.
     */
    public Builder setUNAUTHORIZED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uNAUTHORIZED_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 未授权
     * </pre>
     *
     * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUNAUTHORIZED() {
      uNAUTHORIZED_ = getDefaultInstance().getUNAUTHORIZED();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 未授权
     * </pre>
     *
     * <code>string UNAUTHORIZED = 1 [json_name = "UNAUTHORIZED"];</code>
     * @param value The bytes for uNAUTHORIZED to set.
     * @return This builder for chaining.
     */
    public Builder setUNAUTHORIZEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uNAUTHORIZED_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object tOKENEXPIRED_ = "";
    /**
     * <pre>
     * Token过期
     * </pre>
     *
     * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
     * @return The tOKENEXPIRED.
     */
    public java.lang.String getTOKENEXPIRED() {
      java.lang.Object ref = tOKENEXPIRED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tOKENEXPIRED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Token过期
     * </pre>
     *
     * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
     * @return The bytes for tOKENEXPIRED.
     */
    public com.google.protobuf.ByteString
        getTOKENEXPIREDBytes() {
      java.lang.Object ref = tOKENEXPIRED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tOKENEXPIRED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Token过期
     * </pre>
     *
     * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
     * @param value The tOKENEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENEXPIRED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tOKENEXPIRED_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token过期
     * </pre>
     *
     * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTOKENEXPIRED() {
      tOKENEXPIRED_ = getDefaultInstance().getTOKENEXPIRED();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token过期
     * </pre>
     *
     * <code>string TOKEN_EXPIRED = 2 [json_name = "TOKENEXPIRED"];</code>
     * @param value The bytes for tOKENEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENEXPIREDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tOKENEXPIRED_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tOKENINVALID_ = "";
    /**
     * <pre>
     * Token无效
     * </pre>
     *
     * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
     * @return The tOKENINVALID.
     */
    public java.lang.String getTOKENINVALID() {
      java.lang.Object ref = tOKENINVALID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tOKENINVALID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Token无效
     * </pre>
     *
     * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
     * @return The bytes for tOKENINVALID.
     */
    public com.google.protobuf.ByteString
        getTOKENINVALIDBytes() {
      java.lang.Object ref = tOKENINVALID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tOKENINVALID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Token无效
     * </pre>
     *
     * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
     * @param value The tOKENINVALID to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENINVALID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tOKENINVALID_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token无效
     * </pre>
     *
     * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTOKENINVALID() {
      tOKENINVALID_ = getDefaultInstance().getTOKENINVALID();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token无效
     * </pre>
     *
     * <code>string TOKEN_INVALID = 3 [json_name = "TOKENINVALID"];</code>
     * @param value The bytes for tOKENINVALID to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENINVALIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tOKENINVALID_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object pERMISSIONDENIED_ = "";
    /**
     * <pre>
     * 权限不足
     * </pre>
     *
     * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
     * @return The pERMISSIONDENIED.
     */
    public java.lang.String getPERMISSIONDENIED() {
      java.lang.Object ref = pERMISSIONDENIED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pERMISSIONDENIED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 权限不足
     * </pre>
     *
     * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
     * @return The bytes for pERMISSIONDENIED.
     */
    public com.google.protobuf.ByteString
        getPERMISSIONDENIEDBytes() {
      java.lang.Object ref = pERMISSIONDENIED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pERMISSIONDENIED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 权限不足
     * </pre>
     *
     * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
     * @param value The pERMISSIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setPERMISSIONDENIED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pERMISSIONDENIED_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 权限不足
     * </pre>
     *
     * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPERMISSIONDENIED() {
      pERMISSIONDENIED_ = getDefaultInstance().getPERMISSIONDENIED();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 权限不足
     * </pre>
     *
     * <code>string PERMISSION_DENIED = 4 [json_name = "PERMISSIONDENIED"];</code>
     * @param value The bytes for pERMISSIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setPERMISSIONDENIEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pERMISSIONDENIED_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object aCCOUNTNOTFOUND_ = "";
    /**
     * <pre>
     * 账号不存在
     * </pre>
     *
     * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
     * @return The aCCOUNTNOTFOUND.
     */
    public java.lang.String getACCOUNTNOTFOUND() {
      java.lang.Object ref = aCCOUNTNOTFOUND_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aCCOUNTNOTFOUND_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 账号不存在
     * </pre>
     *
     * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
     * @return The bytes for aCCOUNTNOTFOUND.
     */
    public com.google.protobuf.ByteString
        getACCOUNTNOTFOUNDBytes() {
      java.lang.Object ref = aCCOUNTNOTFOUND_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aCCOUNTNOTFOUND_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账号不存在
     * </pre>
     *
     * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
     * @param value The aCCOUNTNOTFOUND to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTNOTFOUND(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aCCOUNTNOTFOUND_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号不存在
     * </pre>
     *
     * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
     * @return This builder for chaining.
     */
    public Builder clearACCOUNTNOTFOUND() {
      aCCOUNTNOTFOUND_ = getDefaultInstance().getACCOUNTNOTFOUND();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号不存在
     * </pre>
     *
     * <code>string ACCOUNT_NOT_FOUND = 5 [json_name = "ACCOUNTNOTFOUND"];</code>
     * @param value The bytes for aCCOUNTNOTFOUND to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTNOTFOUNDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aCCOUNTNOTFOUND_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object wRONGPASSWORD_ = "";
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
     * @return The wRONGPASSWORD.
     */
    public java.lang.String getWRONGPASSWORD() {
      java.lang.Object ref = wRONGPASSWORD_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wRONGPASSWORD_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
     * @return The bytes for wRONGPASSWORD.
     */
    public com.google.protobuf.ByteString
        getWRONGPASSWORDBytes() {
      java.lang.Object ref = wRONGPASSWORD_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wRONGPASSWORD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
     * @param value The wRONGPASSWORD to set.
     * @return This builder for chaining.
     */
    public Builder setWRONGPASSWORD(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      wRONGPASSWORD_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWRONGPASSWORD() {
      wRONGPASSWORD_ = getDefaultInstance().getWRONGPASSWORD();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密码错误
     * </pre>
     *
     * <code>string WRONG_PASSWORD = 6 [json_name = "WRONGPASSWORD"];</code>
     * @param value The bytes for wRONGPASSWORD to set.
     * @return This builder for chaining.
     */
    public Builder setWRONGPASSWORDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      wRONGPASSWORD_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object aCCOUNTDISABLED_ = "";
    /**
     * <pre>
     * 账号已禁用
     * </pre>
     *
     * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
     * @return The aCCOUNTDISABLED.
     */
    public java.lang.String getACCOUNTDISABLED() {
      java.lang.Object ref = aCCOUNTDISABLED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aCCOUNTDISABLED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 账号已禁用
     * </pre>
     *
     * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
     * @return The bytes for aCCOUNTDISABLED.
     */
    public com.google.protobuf.ByteString
        getACCOUNTDISABLEDBytes() {
      java.lang.Object ref = aCCOUNTDISABLED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aCCOUNTDISABLED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账号已禁用
     * </pre>
     *
     * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
     * @param value The aCCOUNTDISABLED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTDISABLED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aCCOUNTDISABLED_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已禁用
     * </pre>
     *
     * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearACCOUNTDISABLED() {
      aCCOUNTDISABLED_ = getDefaultInstance().getACCOUNTDISABLED();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已禁用
     * </pre>
     *
     * <code>string ACCOUNT_DISABLED = 7 [json_name = "ACCOUNTDISABLED"];</code>
     * @param value The bytes for aCCOUNTDISABLED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTDISABLEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aCCOUNTDISABLED_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object lOGINREQUIRED_ = "";
    /**
     * <pre>
     * 需要登录
     * </pre>
     *
     * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
     * @return The lOGINREQUIRED.
     */
    public java.lang.String getLOGINREQUIRED() {
      java.lang.Object ref = lOGINREQUIRED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lOGINREQUIRED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 需要登录
     * </pre>
     *
     * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
     * @return The bytes for lOGINREQUIRED.
     */
    public com.google.protobuf.ByteString
        getLOGINREQUIREDBytes() {
      java.lang.Object ref = lOGINREQUIRED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lOGINREQUIRED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 需要登录
     * </pre>
     *
     * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
     * @param value The lOGINREQUIRED to set.
     * @return This builder for chaining.
     */
    public Builder setLOGINREQUIRED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lOGINREQUIRED_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 需要登录
     * </pre>
     *
     * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLOGINREQUIRED() {
      lOGINREQUIRED_ = getDefaultInstance().getLOGINREQUIRED();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 需要登录
     * </pre>
     *
     * <code>string LOGIN_REQUIRED = 8 [json_name = "LOGINREQUIRED"];</code>
     * @param value The bytes for lOGINREQUIRED to set.
     * @return This builder for chaining.
     */
    public Builder setLOGINREQUIREDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lOGINREQUIRED_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object tOKENMISSING_ = "";
    /**
     * <pre>
     * Token缺失
     * </pre>
     *
     * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
     * @return The tOKENMISSING.
     */
    public java.lang.String getTOKENMISSING() {
      java.lang.Object ref = tOKENMISSING_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tOKENMISSING_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Token缺失
     * </pre>
     *
     * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
     * @return The bytes for tOKENMISSING.
     */
    public com.google.protobuf.ByteString
        getTOKENMISSINGBytes() {
      java.lang.Object ref = tOKENMISSING_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tOKENMISSING_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Token缺失
     * </pre>
     *
     * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
     * @param value The tOKENMISSING to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENMISSING(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tOKENMISSING_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token缺失
     * </pre>
     *
     * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTOKENMISSING() {
      tOKENMISSING_ = getDefaultInstance().getTOKENMISSING();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token缺失
     * </pre>
     *
     * <code>string TOKEN_MISSING = 9 [json_name = "TOKENMISSING"];</code>
     * @param value The bytes for tOKENMISSING to set.
     * @return This builder for chaining.
     */
    public Builder setTOKENMISSINGBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tOKENMISSING_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object sESSIONEXPIRED_ = "";
    /**
     * <pre>
     * 会话过期
     * </pre>
     *
     * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
     * @return The sESSIONEXPIRED.
     */
    public java.lang.String getSESSIONEXPIRED() {
      java.lang.Object ref = sESSIONEXPIRED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sESSIONEXPIRED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 会话过期
     * </pre>
     *
     * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
     * @return The bytes for sESSIONEXPIRED.
     */
    public com.google.protobuf.ByteString
        getSESSIONEXPIREDBytes() {
      java.lang.Object ref = sESSIONEXPIRED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sESSIONEXPIRED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话过期
     * </pre>
     *
     * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
     * @param value The sESSIONEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setSESSIONEXPIRED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sESSIONEXPIRED_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话过期
     * </pre>
     *
     * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSESSIONEXPIRED() {
      sESSIONEXPIRED_ = getDefaultInstance().getSESSIONEXPIRED();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话过期
     * </pre>
     *
     * <code>string SESSION_EXPIRED = 10 [json_name = "SESSIONEXPIRED"];</code>
     * @param value The bytes for sESSIONEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setSESSIONEXPIREDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sESSIONEXPIRED_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object iNVALIDCREDENTIALS_ = "";
    /**
     * <pre>
     * 无效的凭证
     * </pre>
     *
     * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
     * @return The iNVALIDCREDENTIALS.
     */
    public java.lang.String getINVALIDCREDENTIALS() {
      java.lang.Object ref = iNVALIDCREDENTIALS_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iNVALIDCREDENTIALS_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 无效的凭证
     * </pre>
     *
     * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
     * @return The bytes for iNVALIDCREDENTIALS.
     */
    public com.google.protobuf.ByteString
        getINVALIDCREDENTIALSBytes() {
      java.lang.Object ref = iNVALIDCREDENTIALS_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iNVALIDCREDENTIALS_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 无效的凭证
     * </pre>
     *
     * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
     * @param value The iNVALIDCREDENTIALS to set.
     * @return This builder for chaining.
     */
    public Builder setINVALIDCREDENTIALS(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      iNVALIDCREDENTIALS_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 无效的凭证
     * </pre>
     *
     * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearINVALIDCREDENTIALS() {
      iNVALIDCREDENTIALS_ = getDefaultInstance().getINVALIDCREDENTIALS();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 无效的凭证
     * </pre>
     *
     * <code>string INVALID_CREDENTIALS = 11 [json_name = "INVALIDCREDENTIALS"];</code>
     * @param value The bytes for iNVALIDCREDENTIALS to set.
     * @return This builder for chaining.
     */
    public Builder setINVALIDCREDENTIALSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      iNVALIDCREDENTIALS_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object aCCOUNTLOCKED_ = "";
    /**
     * <pre>
     * 账号已锁定
     * </pre>
     *
     * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
     * @return The aCCOUNTLOCKED.
     */
    public java.lang.String getACCOUNTLOCKED() {
      java.lang.Object ref = aCCOUNTLOCKED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aCCOUNTLOCKED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 账号已锁定
     * </pre>
     *
     * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
     * @return The bytes for aCCOUNTLOCKED.
     */
    public com.google.protobuf.ByteString
        getACCOUNTLOCKEDBytes() {
      java.lang.Object ref = aCCOUNTLOCKED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aCCOUNTLOCKED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账号已锁定
     * </pre>
     *
     * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
     * @param value The aCCOUNTLOCKED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTLOCKED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aCCOUNTLOCKED_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已锁定
     * </pre>
     *
     * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearACCOUNTLOCKED() {
      aCCOUNTLOCKED_ = getDefaultInstance().getACCOUNTLOCKED();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已锁定
     * </pre>
     *
     * <code>string ACCOUNT_LOCKED = 12 [json_name = "ACCOUNTLOCKED"];</code>
     * @param value The bytes for aCCOUNTLOCKED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTLOCKEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aCCOUNTLOCKED_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object aCCOUNTEXPIRED_ = "";
    /**
     * <pre>
     * 账号已过期
     * </pre>
     *
     * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
     * @return The aCCOUNTEXPIRED.
     */
    public java.lang.String getACCOUNTEXPIRED() {
      java.lang.Object ref = aCCOUNTEXPIRED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aCCOUNTEXPIRED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 账号已过期
     * </pre>
     *
     * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
     * @return The bytes for aCCOUNTEXPIRED.
     */
    public com.google.protobuf.ByteString
        getACCOUNTEXPIREDBytes() {
      java.lang.Object ref = aCCOUNTEXPIRED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aCCOUNTEXPIRED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账号已过期
     * </pre>
     *
     * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
     * @param value The aCCOUNTEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTEXPIRED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      aCCOUNTEXPIRED_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已过期
     * </pre>
     *
     * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearACCOUNTEXPIRED() {
      aCCOUNTEXPIRED_ = getDefaultInstance().getACCOUNTEXPIRED();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账号已过期
     * </pre>
     *
     * <code>string ACCOUNT_EXPIRED = 13 [json_name = "ACCOUNTEXPIRED"];</code>
     * @param value The bytes for aCCOUNTEXPIRED to set.
     * @return This builder for chaining.
     */
    public Builder setACCOUNTEXPIREDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      aCCOUNTEXPIRED_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object iNVALIDLOGINTYPE_ = "";
    /**
     * <pre>
     * 无效的登录类型
     * </pre>
     *
     * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
     * @return The iNVALIDLOGINTYPE.
     */
    public java.lang.String getINVALIDLOGINTYPE() {
      java.lang.Object ref = iNVALIDLOGINTYPE_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iNVALIDLOGINTYPE_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 无效的登录类型
     * </pre>
     *
     * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
     * @return The bytes for iNVALIDLOGINTYPE.
     */
    public com.google.protobuf.ByteString
        getINVALIDLOGINTYPEBytes() {
      java.lang.Object ref = iNVALIDLOGINTYPE_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iNVALIDLOGINTYPE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 无效的登录类型
     * </pre>
     *
     * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
     * @param value The iNVALIDLOGINTYPE to set.
     * @return This builder for chaining.
     */
    public Builder setINVALIDLOGINTYPE(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      iNVALIDLOGINTYPE_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 无效的登录类型
     * </pre>
     *
     * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
     * @return This builder for chaining.
     */
    public Builder clearINVALIDLOGINTYPE() {
      iNVALIDLOGINTYPE_ = getDefaultInstance().getINVALIDLOGINTYPE();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 无效的登录类型
     * </pre>
     *
     * <code>string INVALID_LOGIN_TYPE = 14 [json_name = "INVALIDLOGINTYPE"];</code>
     * @param value The bytes for iNVALIDLOGINTYPE to set.
     * @return This builder for chaining.
     */
    public Builder setINVALIDLOGINTYPEBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      iNVALIDLOGINTYPE_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.AuthErrorMessages)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.AuthErrorMessages)
  private static final com.rankquantity.voyager.api.AuthErrorMessages DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.AuthErrorMessages();
  }

  public static com.rankquantity.voyager.api.AuthErrorMessages getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthErrorMessages>
      PARSER = new com.google.protobuf.AbstractParser<AuthErrorMessages>() {
    @java.lang.Override
    public AuthErrorMessages parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthErrorMessages> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthErrorMessages> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.AuthErrorMessages getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

