// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface ChatContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.ChatContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 chat_id = 1 [json_name = "chatId"];</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>int64 role_id = 2 [json_name = "roleId"];</code>
   * @return The roleId.
   */
  long getRoleId();

  /**
   * <code>int64 user_id = 3 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 timestamp = 4 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int64 last_update_time = 5 [json_name = "lastUpdateTime"];</code>
   * @return The lastUpdateTime.
   */
  long getLastUpdateTime();

  /**
   * <code>int64 total_tokens = 6 [json_name = "totalTokens"];</code>
   * @return The totalTokens.
   */
  long getTotalTokens();

  /**
   * <code>int64 total_messages = 7 [json_name = "totalMessages"];</code>
   * @return The totalMessages.
   */
  long getTotalMessages();

  /**
   * <code>.rankquantity.voyager.api.ChatMessage last_message = 8 [json_name = "lastMessage"];</code>
   * @return Whether the lastMessage field is set.
   */
  boolean hasLastMessage();
  /**
   * <code>.rankquantity.voyager.api.ChatMessage last_message = 8 [json_name = "lastMessage"];</code>
   * @return The lastMessage.
   */
  com.rankquantity.voyager.api.ChatMessage getLastMessage();
  /**
   * <code>.rankquantity.voyager.api.ChatMessage last_message = 8 [json_name = "lastMessage"];</code>
   */
  com.rankquantity.voyager.api.ChatMessageOrBuilder getLastMessageOrBuilder();

  /**
   * <code>.rankquantity.voyager.api.UserInfo user = 9 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.rankquantity.voyager.api.UserInfo user = 9 [json_name = "user"];</code>
   * @return The user.
   */
  com.rankquantity.voyager.api.UserInfo getUser();
  /**
   * <code>.rankquantity.voyager.api.UserInfo user = 9 [json_name = "user"];</code>
   */
  com.rankquantity.voyager.api.UserInfoOrBuilder getUserOrBuilder();

  /**
   * <code>.rankquantity.voyager.api.StoryRole role = 10 [json_name = "role"];</code>
   * @return Whether the role field is set.
   */
  boolean hasRole();
  /**
   * <code>.rankquantity.voyager.api.StoryRole role = 10 [json_name = "role"];</code>
   * @return The role.
   */
  com.rankquantity.voyager.api.StoryRole getRole();
  /**
   * <code>.rankquantity.voyager.api.StoryRole role = 10 [json_name = "role"];</code>
   */
  com.rankquantity.voyager.api.StoryRoleOrBuilder getRoleOrBuilder();
}
