// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface CreateStoryCommentReplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.CreateStoryCommentReplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 comment_id = 1 [json_name = "commentId"];</code>
   * @return The commentId.
   */
  long getCommentId();

  /**
   * <code>int64 user_id = 2 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string content = 3 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
