// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * <pre>
 * ==================== 删除用户故事板草稿 ====================
 * 删除用户故事板草稿请求
 * </pre>
 *
 * Protobuf type {@code rankquantity.voyager.api.DeleteUserStoryboardDraftRequest}
 */
@com.google.protobuf.Generated
public final class DeleteUserStoryboardDraftRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)
    DeleteUserStoryboardDraftRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      DeleteUserStoryboardDraftRequest.class.getName());
  }
  // Use DeleteUserStoryboardDraftRequest.newBuilder() to construct.
  private DeleteUserStoryboardDraftRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DeleteUserStoryboardDraftRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.ServiceProto.internal_static_rankquantity_voyager_api_DeleteUserStoryboardDraftRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.ServiceProto.internal_static_rankquantity_voyager_api_DeleteUserStoryboardDraftRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.class, com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int DRAFT_ID_FIELD_NUMBER = 2;
  private long draftId_ = 0L;
  /**
   * <pre>
   * 草稿ID
   * </pre>
   *
   * <code>int64 draft_id = 2 [json_name = "draftId"];</code>
   * @return The draftId.
   */
  @java.lang.Override
  public long getDraftId() {
    return draftId_;
  }

  public static final int STORY_ID_FIELD_NUMBER = 3;
  private long storyId_ = 0L;
  /**
   * <pre>
   * 故事ID（可选）
   * </pre>
   *
   * <code>int64 story_id = 3 [json_name = "storyId"];</code>
   * @return The storyId.
   */
  @java.lang.Override
  public long getStoryId() {
    return storyId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (draftId_ != 0L) {
      output.writeInt64(2, draftId_);
    }
    if (storyId_ != 0L) {
      output.writeInt64(3, storyId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (draftId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, draftId_);
    }
    if (storyId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, storyId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest other = (com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getDraftId()
        != other.getDraftId()) return false;
    if (getStoryId()
        != other.getStoryId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + DRAFT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDraftId());
    hash = (37 * hash) + STORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStoryId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ==================== 删除用户故事板草稿 ====================
   * 删除用户故事板草稿请求
   * </pre>
   *
   * Protobuf type {@code rankquantity.voyager.api.DeleteUserStoryboardDraftRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)
      com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.ServiceProto.internal_static_rankquantity_voyager_api_DeleteUserStoryboardDraftRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.ServiceProto.internal_static_rankquantity_voyager_api_DeleteUserStoryboardDraftRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.class, com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      draftId_ = 0L;
      storyId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.ServiceProto.internal_static_rankquantity_voyager_api_DeleteUserStoryboardDraftRequest_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest build() {
      com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest buildPartial() {
      com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest result = new com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.draftId_ = draftId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.storyId_ = storyId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest) {
        return mergeFrom((com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest other) {
      if (other == com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getDraftId() != 0L) {
        setDraftId(other.getDraftId());
      }
      if (other.getStoryId() != 0L) {
        setStoryId(other.getStoryId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              draftId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              storyId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long draftId_ ;
    /**
     * <pre>
     * 草稿ID
     * </pre>
     *
     * <code>int64 draft_id = 2 [json_name = "draftId"];</code>
     * @return The draftId.
     */
    @java.lang.Override
    public long getDraftId() {
      return draftId_;
    }
    /**
     * <pre>
     * 草稿ID
     * </pre>
     *
     * <code>int64 draft_id = 2 [json_name = "draftId"];</code>
     * @param value The draftId to set.
     * @return This builder for chaining.
     */
    public Builder setDraftId(long value) {

      draftId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 草稿ID
     * </pre>
     *
     * <code>int64 draft_id = 2 [json_name = "draftId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDraftId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      draftId_ = 0L;
      onChanged();
      return this;
    }

    private long storyId_ ;
    /**
     * <pre>
     * 故事ID（可选）
     * </pre>
     *
     * <code>int64 story_id = 3 [json_name = "storyId"];</code>
     * @return The storyId.
     */
    @java.lang.Override
    public long getStoryId() {
      return storyId_;
    }
    /**
     * <pre>
     * 故事ID（可选）
     * </pre>
     *
     * <code>int64 story_id = 3 [json_name = "storyId"];</code>
     * @param value The storyId to set.
     * @return This builder for chaining.
     */
    public Builder setStoryId(long value) {

      storyId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事ID（可选）
     * </pre>
     *
     * <code>int64 story_id = 3 [json_name = "storyId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoryId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      storyId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.DeleteUserStoryboardDraftRequest)
  private static final com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest();
  }

  public static com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteUserStoryboardDraftRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeleteUserStoryboardDraftRequest>() {
    @java.lang.Override
    public DeleteUserStoryboardDraftRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeleteUserStoryboardDraftRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteUserStoryboardDraftRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.DeleteUserStoryboardDraftRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

