// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface FetchGroupMembersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.FetchGroupMembersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 group_id = 1 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>int64 offset = 2 [json_name = "offset"];</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>int64 page_size = 3 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  long getPageSize();
}
