// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface GetStoryRolesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.GetStoryRolesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.rankquantity.voyager.api.GetStoryRolesResponse.Data data = 3 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.rankquantity.voyager.api.GetStoryRolesResponse.Data data = 3 [json_name = "data"];</code>
   * @return The data.
   */
  com.rankquantity.voyager.api.GetStoryRolesResponse.Data getData();
  /**
   * <code>.rankquantity.voyager.api.GetStoryRolesResponse.Data data = 3 [json_name = "data"];</code>
   */
  com.rankquantity.voyager.api.GetStoryRolesResponse.DataOrBuilder getDataOrBuilder();
}
