// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * Protobuf type {@code rankquantity.voyager.api.LikeStoryboardResponse}
 */
@com.google.protobuf.Generated
public final class LikeStoryboardResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.LikeStoryboardResponse)
    LikeStoryboardResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      LikeStoryboardResponse.class.getName());
  }
  // Use LikeStoryboardResponse.newBuilder() to construct.
  private LikeStoryboardResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LikeStoryboardResponse() {
    message_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.LikeStoryboardResponse.class, com.rankquantity.voyager.api.LikeStoryboardResponse.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.LikeStoryboardResponse.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 story_id = 1 [json_name = "storyId"];</code>
     * @return The storyId.
     */
    long getStoryId();

    /**
     * <code>int64 board_id = 2 [json_name = "boardId"];</code>
     * @return The boardId.
     */
    long getBoardId();

    /**
     * <code>int64 user_id = 3 [json_name = "userId"];</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int64 like_num = 4 [json_name = "likeNum"];</code>
     * @return The likeNum.
     */
    long getLikeNum();
  }
  /**
   * Protobuf type {@code rankquantity.voyager.api.LikeStoryboardResponse.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.LikeStoryboardResponse.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        Data.class.getName());
    }
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.LikeStoryboardResponse.Data.class, com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder.class);
    }

    public static final int STORY_ID_FIELD_NUMBER = 1;
    private long storyId_ = 0L;
    /**
     * <code>int64 story_id = 1 [json_name = "storyId"];</code>
     * @return The storyId.
     */
    @java.lang.Override
    public long getStoryId() {
      return storyId_;
    }

    public static final int BOARD_ID_FIELD_NUMBER = 2;
    private long boardId_ = 0L;
    /**
     * <code>int64 board_id = 2 [json_name = "boardId"];</code>
     * @return The boardId.
     */
    @java.lang.Override
    public long getBoardId() {
      return boardId_;
    }

    public static final int USER_ID_FIELD_NUMBER = 3;
    private long userId_ = 0L;
    /**
     * <code>int64 user_id = 3 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int LIKE_NUM_FIELD_NUMBER = 4;
    private long likeNum_ = 0L;
    /**
     * <code>int64 like_num = 4 [json_name = "likeNum"];</code>
     * @return The likeNum.
     */
    @java.lang.Override
    public long getLikeNum() {
      return likeNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (storyId_ != 0L) {
        output.writeInt64(1, storyId_);
      }
      if (boardId_ != 0L) {
        output.writeInt64(2, boardId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (likeNum_ != 0L) {
        output.writeInt64(4, likeNum_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (storyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, storyId_);
      }
      if (boardId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, boardId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (likeNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, likeNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rankquantity.voyager.api.LikeStoryboardResponse.Data)) {
        return super.equals(obj);
      }
      com.rankquantity.voyager.api.LikeStoryboardResponse.Data other = (com.rankquantity.voyager.api.LikeStoryboardResponse.Data) obj;

      if (getStoryId()
          != other.getStoryId()) return false;
      if (getBoardId()
          != other.getBoardId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getLikeNum()
          != other.getLikeNum()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STORY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStoryId());
      hash = (37 * hash) + BOARD_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBoardId());
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + LIKE_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLikeNum());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rankquantity.voyager.api.LikeStoryboardResponse.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rankquantity.voyager.api.LikeStoryboardResponse.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.LikeStoryboardResponse.Data)
        com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rankquantity.voyager.api.LikeStoryboardResponse.Data.class, com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder.class);
      }

      // Construct using com.rankquantity.voyager.api.LikeStoryboardResponse.Data.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        storyId_ = 0L;
        boardId_ = 0L;
        userId_ = 0L;
        likeNum_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_Data_descriptor;
      }

      @java.lang.Override
      public com.rankquantity.voyager.api.LikeStoryboardResponse.Data getDefaultInstanceForType() {
        return com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.rankquantity.voyager.api.LikeStoryboardResponse.Data build() {
        com.rankquantity.voyager.api.LikeStoryboardResponse.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rankquantity.voyager.api.LikeStoryboardResponse.Data buildPartial() {
        com.rankquantity.voyager.api.LikeStoryboardResponse.Data result = new com.rankquantity.voyager.api.LikeStoryboardResponse.Data(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.rankquantity.voyager.api.LikeStoryboardResponse.Data result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.storyId_ = storyId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.boardId_ = boardId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.likeNum_ = likeNum_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rankquantity.voyager.api.LikeStoryboardResponse.Data) {
          return mergeFrom((com.rankquantity.voyager.api.LikeStoryboardResponse.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rankquantity.voyager.api.LikeStoryboardResponse.Data other) {
        if (other == com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance()) return this;
        if (other.getStoryId() != 0L) {
          setStoryId(other.getStoryId());
        }
        if (other.getBoardId() != 0L) {
          setBoardId(other.getBoardId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getLikeNum() != 0L) {
          setLikeNum(other.getLikeNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                storyId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                boardId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                likeNum_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long storyId_ ;
      /**
       * <code>int64 story_id = 1 [json_name = "storyId"];</code>
       * @return The storyId.
       */
      @java.lang.Override
      public long getStoryId() {
        return storyId_;
      }
      /**
       * <code>int64 story_id = 1 [json_name = "storyId"];</code>
       * @param value The storyId to set.
       * @return This builder for chaining.
       */
      public Builder setStoryId(long value) {

        storyId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 story_id = 1 [json_name = "storyId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStoryId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        storyId_ = 0L;
        onChanged();
        return this;
      }

      private long boardId_ ;
      /**
       * <code>int64 board_id = 2 [json_name = "boardId"];</code>
       * @return The boardId.
       */
      @java.lang.Override
      public long getBoardId() {
        return boardId_;
      }
      /**
       * <code>int64 board_id = 2 [json_name = "boardId"];</code>
       * @param value The boardId to set.
       * @return This builder for chaining.
       */
      public Builder setBoardId(long value) {

        boardId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 board_id = 2 [json_name = "boardId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBoardId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boardId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 3 [json_name = "userId"];</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 3 [json_name = "userId"];</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 3 [json_name = "userId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long likeNum_ ;
      /**
       * <code>int64 like_num = 4 [json_name = "likeNum"];</code>
       * @return The likeNum.
       */
      @java.lang.Override
      public long getLikeNum() {
        return likeNum_;
      }
      /**
       * <code>int64 like_num = 4 [json_name = "likeNum"];</code>
       * @param value The likeNum to set.
       * @return This builder for chaining.
       */
      public Builder setLikeNum(long value) {

        likeNum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 like_num = 4 [json_name = "likeNum"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLikeNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        likeNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.LikeStoryboardResponse.Data)
    }

    // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.LikeStoryboardResponse.Data)
    private static final com.rankquantity.voyager.api.LikeStoryboardResponse.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rankquantity.voyager.api.LikeStoryboardResponse.Data();
    }

    public static com.rankquantity.voyager.api.LikeStoryboardResponse.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.LikeStoryboardResponse.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <code>int32 code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.rankquantity.voyager.api.LikeStoryboardResponse.Data data_;
  /**
   * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
   * @return The data.
   */
  @java.lang.Override
  public com.rankquantity.voyager.api.LikeStoryboardResponse.Data getData() {
    return data_ == null ? com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder getDataOrBuilder() {
    return data_ == null ? com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance() : data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.LikeStoryboardResponse)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.LikeStoryboardResponse other = (com.rankquantity.voyager.api.LikeStoryboardResponse) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.LikeStoryboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.LikeStoryboardResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rankquantity.voyager.api.LikeStoryboardResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.LikeStoryboardResponse)
      com.rankquantity.voyager.api.LikeStoryboardResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.LikeStoryboardResponse.class, com.rankquantity.voyager.api.LikeStoryboardResponse.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.LikeStoryboardResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      message_ = "";
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_LikeStoryboardResponse_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.LikeStoryboardResponse getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.LikeStoryboardResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.LikeStoryboardResponse build() {
      com.rankquantity.voyager.api.LikeStoryboardResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.LikeStoryboardResponse buildPartial() {
      com.rankquantity.voyager.api.LikeStoryboardResponse result = new com.rankquantity.voyager.api.LikeStoryboardResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.LikeStoryboardResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.LikeStoryboardResponse) {
        return mergeFrom((com.rankquantity.voyager.api.LikeStoryboardResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.LikeStoryboardResponse other) {
      if (other == com.rankquantity.voyager.api.LikeStoryboardResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1 [json_name = "code"];</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {

      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.rankquantity.voyager.api.LikeStoryboardResponse.Data data_;
    private com.google.protobuf.SingleFieldBuilder<
        com.rankquantity.voyager.api.LikeStoryboardResponse.Data, com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder, com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder> dataBuilder_;
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     * @return The data.
     */
    public com.rankquantity.voyager.api.LikeStoryboardResponse.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder setData(com.rankquantity.voyager.api.LikeStoryboardResponse.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder setData(
        com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder mergeData(com.rankquantity.voyager.api.LikeStoryboardResponse.Data value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          data_ != null &&
          data_ != com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      if (data_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder getDataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    public com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.rankquantity.voyager.api.LikeStoryboardResponse.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.rankquantity.voyager.api.LikeStoryboardResponse.Data data = 3 [json_name = "data"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.rankquantity.voyager.api.LikeStoryboardResponse.Data, com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder, com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.rankquantity.voyager.api.LikeStoryboardResponse.Data, com.rankquantity.voyager.api.LikeStoryboardResponse.Data.Builder, com.rankquantity.voyager.api.LikeStoryboardResponse.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.LikeStoryboardResponse)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.LikeStoryboardResponse)
  private static final com.rankquantity.voyager.api.LikeStoryboardResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.LikeStoryboardResponse();
  }

  public static com.rankquantity.voyager.api.LikeStoryboardResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LikeStoryboardResponse>
      PARSER = new com.google.protobuf.AbstractParser<LikeStoryboardResponse>() {
    @java.lang.Override
    public LikeStoryboardResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LikeStoryboardResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LikeStoryboardResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.LikeStoryboardResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

