// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: error.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface LikeErrorMessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.LikeErrorMessages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 点赞不存在
   * </pre>
   *
   * <code>string LIKE_NOT_FOUND = 1 [json_name = "LIKENOTFOUND"];</code>
   * @return The lIKENOTFOUND.
   */
  java.lang.String getLIKENOTFOUND();
  /**
   * <pre>
   * 点赞不存在
   * </pre>
   *
   * <code>string LIKE_NOT_FOUND = 1 [json_name = "LIKENOTFOUND"];</code>
   * @return The bytes for lIKENOTFOUND.
   */
  com.google.protobuf.ByteString
      getLIKENOTFOUNDBytes();

  /**
   * <pre>
   * 点赞已存在
   * </pre>
   *
   * <code>string LIKE_ALREADY_EXISTS = 2 [json_name = "LIKEALREADYEXISTS"];</code>
   * @return The lIKEALREADYEXISTS.
   */
  java.lang.String getLIKEALREADYEXISTS();
  /**
   * <pre>
   * 点赞已存在
   * </pre>
   *
   * <code>string LIKE_ALREADY_EXISTS = 2 [json_name = "LIKEALREADYEXISTS"];</code>
   * @return The bytes for lIKEALREADYEXISTS.
   */
  com.google.protobuf.ByteString
      getLIKEALREADYEXISTSBytes();

  /**
   * <pre>
   * 点赞权限不足
   * </pre>
   *
   * <code>string LIKE_PERMISSION_DENIED = 3 [json_name = "LIKEPERMISSIONDENIED"];</code>
   * @return The lIKEPERMISSIONDENIED.
   */
  java.lang.String getLIKEPERMISSIONDENIED();
  /**
   * <pre>
   * 点赞权限不足
   * </pre>
   *
   * <code>string LIKE_PERMISSION_DENIED = 3 [json_name = "LIKEPERMISSIONDENIED"];</code>
   * @return The bytes for lIKEPERMISSIONDENIED.
   */
  com.google.protobuf.ByteString
      getLIKEPERMISSIONDENIEDBytes();

  /**
   * <pre>
   * 点赞已锁定
   * </pre>
   *
   * <code>string LIKE_LOCKED = 4 [json_name = "LIKELOCKED"];</code>
   * @return The lIKELOCKED.
   */
  java.lang.String getLIKELOCKED();
  /**
   * <pre>
   * 点赞已锁定
   * </pre>
   *
   * <code>string LIKE_LOCKED = 4 [json_name = "LIKELOCKED"];</code>
   * @return The bytes for lIKELOCKED.
   */
  com.google.protobuf.ByteString
      getLIKELOCKEDBytes();

  /**
   * <pre>
   * 点赞状态错误
   * </pre>
   *
   * <code>string LIKE_STATUS_ERROR = 5 [json_name = "LIKESTATUSERROR"];</code>
   * @return The lIKESTATUSERROR.
   */
  java.lang.String getLIKESTATUSERROR();
  /**
   * <pre>
   * 点赞状态错误
   * </pre>
   *
   * <code>string LIKE_STATUS_ERROR = 5 [json_name = "LIKESTATUSERROR"];</code>
   * @return The bytes for lIKESTATUSERROR.
   */
  com.google.protobuf.ByteString
      getLIKESTATUSERRORBytes();
}
