// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface RestoreStoryboardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.RestoreStoryboardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rankquantity.voyager.api.ResponseCode code = 1 [json_name = "code"];</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.rankquantity.voyager.api.ResponseCode code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  com.rankquantity.voyager.api.ResponseCode getCode();

  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.rankquantity.voyager.api.StoryboardStageStore store = 3 [json_name = "store"];</code>
   * @return Whether the store field is set.
   */
  boolean hasStore();
  /**
   * <code>.rankquantity.voyager.api.StoryboardStageStore store = 3 [json_name = "store"];</code>
   * @return The store.
   */
  com.rankquantity.voyager.api.StoryboardStageStore getStore();
  /**
   * <code>.rankquantity.voyager.api.StoryboardStageStore store = 3 [json_name = "store"];</code>
   */
  com.rankquantity.voyager.api.StoryboardStageStoreOrBuilder getStoreOrBuilder();
}
