// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface StoryNameAndThemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.StoryNameAndTheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;345&#92;220&#92;215&#92;347&#92;247&#92;260"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;345&#92;220&#92;215&#92;347&#92;247&#92;260"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string theme = 2 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;344&#92;270&#92;273&#92;351&#92;242&#92;230"];</code>
   * @return The theme.
   */
  java.lang.String getTheme();
  /**
   * <code>string theme = 2 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;344&#92;270&#92;273&#92;351&#92;242&#92;230"];</code>
   * @return The bytes for theme.
   */
  com.google.protobuf.ByteString
      getThemeBytes();

  /**
   * <code>string description = 3 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;347&#92;256&#92;200&#92;344&#92;273&#92;213"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3 [json_name = "&#92;346&#92;225&#92;205&#92;344&#92;272&#92;213&#92;347&#92;256&#92;200&#92;344&#92;273&#92;213"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
