// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface StoryBoardSenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.StoryBoardSence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sence_id = 1 [json_name = "senceId"];</code>
   * @return The senceId.
   */
  long getSenceId();

  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>repeated string character_ids = 3 [json_name = "characterIds"];</code>
   * @return A list containing the characterIds.
   */
  java.util.List<java.lang.String>
      getCharacterIdsList();
  /**
   * <code>repeated string character_ids = 3 [json_name = "characterIds"];</code>
   * @return The count of characterIds.
   */
  int getCharacterIdsCount();
  /**
   * <code>repeated string character_ids = 3 [json_name = "characterIds"];</code>
   * @param index The index of the element to return.
   * @return The characterIds at the given index.
   */
  java.lang.String getCharacterIds(int index);
  /**
   * <code>repeated string character_ids = 3 [json_name = "characterIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the characterIds at the given index.
   */
  com.google.protobuf.ByteString
      getCharacterIdsBytes(int index);

  /**
   * <code>int64 creator_id = 4 [json_name = "creatorId"];</code>
   * @return The creatorId.
   */
  long getCreatorId();

  /**
   * <code>int64 story_id = 5 [json_name = "storyId"];</code>
   * @return The storyId.
   */
  long getStoryId();

  /**
   * <code>int64 board_id = 6 [json_name = "boardId"];</code>
   * @return The boardId.
   */
  long getBoardId();

  /**
   * <code>string image_prompts = 7 [json_name = "imagePrompts"];</code>
   * @return The imagePrompts.
   */
  java.lang.String getImagePrompts();
  /**
   * <code>string image_prompts = 7 [json_name = "imagePrompts"];</code>
   * @return The bytes for imagePrompts.
   */
  com.google.protobuf.ByteString
      getImagePromptsBytes();

  /**
   * <code>string audio_prompts = 8 [json_name = "audioPrompts"];</code>
   * @return The audioPrompts.
   */
  java.lang.String getAudioPrompts();
  /**
   * <code>string audio_prompts = 8 [json_name = "audioPrompts"];</code>
   * @return The bytes for audioPrompts.
   */
  com.google.protobuf.ByteString
      getAudioPromptsBytes();

  /**
   * <code>string video_prompts = 9 [json_name = "videoPrompts"];</code>
   * @return The videoPrompts.
   */
  java.lang.String getVideoPrompts();
  /**
   * <code>string video_prompts = 9 [json_name = "videoPrompts"];</code>
   * @return The bytes for videoPrompts.
   */
  com.google.protobuf.ByteString
      getVideoPromptsBytes();

  /**
   * <code>int32 is_generating = 10 [json_name = "isGenerating"];</code>
   * @return The isGenerating.
   */
  int getIsGenerating();

  /**
   * <code>repeated string images = 11 [json_name = "images"];</code>
   * @return A list containing the images.
   */
  java.util.List<java.lang.String>
      getImagesList();
  /**
   * <code>repeated string images = 11 [json_name = "images"];</code>
   * @return The count of images.
   */
  int getImagesCount();
  /**
   * <code>repeated string images = 11 [json_name = "images"];</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  java.lang.String getImages(int index);
  /**
   * <code>repeated string images = 11 [json_name = "images"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the images at the given index.
   */
  com.google.protobuf.ByteString
      getImagesBytes(int index);

  /**
   * <code>string image_url = 12 [json_name = "imageUrl"];</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 12 [json_name = "imageUrl"];</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>string audio_url = 13 [json_name = "audioUrl"];</code>
   * @return The audioUrl.
   */
  java.lang.String getAudioUrl();
  /**
   * <code>string audio_url = 13 [json_name = "audioUrl"];</code>
   * @return The bytes for audioUrl.
   */
  com.google.protobuf.ByteString
      getAudioUrlBytes();

  /**
   * <code>string video_url = 14 [json_name = "videoUrl"];</code>
   * @return The videoUrl.
   */
  java.lang.String getVideoUrl();
  /**
   * <code>string video_url = 14 [json_name = "videoUrl"];</code>
   * @return The bytes for videoUrl.
   */
  com.google.protobuf.ByteString
      getVideoUrlBytes();

  /**
   * <code>int32 status = 15 [json_name = "status"];</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int64 Ctime = 16 [json_name = "Ctime"];</code>
   * @return The ctime.
   */
  long getCtime();

  /**
   * <code>int64 Mtime = 17 [json_name = "Mtime"];</code>
   * @return The mtime.
   */
  long getMtime();
}
