// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface StorySummaryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.StorySummaryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 故事ID
   * </pre>
   *
   * <code>int64 story_id = 1 [json_name = "storyId"];</code>
   * @return The storyId.
   */
  long getStoryId();

  /**
   * <pre>
   * 故事标题
   * </pre>
   *
   * <code>string story_title = 2 [json_name = "storyTitle"];</code>
   * @return The storyTitle.
   */
  java.lang.String getStoryTitle();
  /**
   * <pre>
   * 故事标题
   * </pre>
   *
   * <code>string story_title = 2 [json_name = "storyTitle"];</code>
   * @return The bytes for storyTitle.
   */
  com.google.protobuf.ByteString
      getStoryTitleBytes();

  /**
   * <pre>
   * 故事头像
   * </pre>
   *
   * <code>string story_avatar = 3 [json_name = "storyAvatar"];</code>
   * @return The storyAvatar.
   */
  java.lang.String getStoryAvatar();
  /**
   * <pre>
   * 故事头像
   * </pre>
   *
   * <code>string story_avatar = 3 [json_name = "storyAvatar"];</code>
   * @return The bytes for storyAvatar.
   */
  com.google.protobuf.ByteString
      getStoryAvatarBytes();

  /**
   * <pre>
   * 故事描述
   * </pre>
   *
   * <code>string story_description = 4 [json_name = "storyDescription"];</code>
   * @return The storyDescription.
   */
  java.lang.String getStoryDescription();
  /**
   * <pre>
   * 故事描述
   * </pre>
   *
   * <code>string story_description = 4 [json_name = "storyDescription"];</code>
   * @return The bytes for storyDescription.
   */
  com.google.protobuf.ByteString
      getStoryDescriptionBytes();

  /**
   * <pre>
   * 故事封面
   * </pre>
   *
   * <code>string story_cover = 5 [json_name = "storyCover"];</code>
   * @return The storyCover.
   */
  java.lang.String getStoryCover();
  /**
   * <pre>
   * 故事封面
   * </pre>
   *
   * <code>string story_cover = 5 [json_name = "storyCover"];</code>
   * @return The bytes for storyCover.
   */
  com.google.protobuf.ByteString
      getStoryCoverBytes();

  /**
   * <pre>
   * 故事标签
   * </pre>
   *
   * <code>string story_tags = 6 [json_name = "storyTags"];</code>
   * @return The storyTags.
   */
  java.lang.String getStoryTags();
  /**
   * <pre>
   * 故事标签
   * </pre>
   *
   * <code>string story_tags = 6 [json_name = "storyTags"];</code>
   * @return The bytes for storyTags.
   */
  com.google.protobuf.ByteString
      getStoryTagsBytes();

  /**
   * <pre>
   * 创建时间
   * </pre>
   *
   * <code>int64 create_time = 7 [json_name = "createTime"];</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <pre>
   * 创建用户ID
   * </pre>
   *
   * <code>int64 create_user_id = 8 [json_name = "createUserId"];</code>
   * @return The createUserId.
   */
  long getCreateUserId();

  /**
   * <pre>
   * 故事板总数
   * </pre>
   *
   * <code>int64 total_board_count = 9 [json_name = "totalBoardCount"];</code>
   * @return The totalBoardCount.
   */
  long getTotalBoardCount();

  /**
   * <pre>
   * 点赞总数
   * </pre>
   *
   * <code>int64 total_like_count = 10 [json_name = "totalLikeCount"];</code>
   * @return The totalLikeCount.
   */
  long getTotalLikeCount();

  /**
   * <pre>
   * 评论总数
   * </pre>
   *
   * <code>int64 total_comment_count = 11 [json_name = "totalCommentCount"];</code>
   * @return The totalCommentCount.
   */
  long getTotalCommentCount();

  /**
   * <pre>
   * 分享总数
   * </pre>
   *
   * <code>int64 total_share_count = 12 [json_name = "totalShareCount"];</code>
   * @return The totalShareCount.
   */
  long getTotalShareCount();

  /**
   * <pre>
   * 渲染总数
   * </pre>
   *
   * <code>int64 total_render_count = 13 [json_name = "totalRenderCount"];</code>
   * @return The totalRenderCount.
   */
  long getTotalRenderCount();

  /**
   * <pre>
   * 分叉总数
   * </pre>
   *
   * <code>int64 total_fork_count = 14 [json_name = "totalForkCount"];</code>
   * @return The totalForkCount.
   */
  long getTotalForkCount();

  /**
   * <pre>
   * 查看总数
   * </pre>
   *
   * <code>int64 total_view_count = 15 [json_name = "totalViewCount"];</code>
   * @return The totalViewCount.
   */
  long getTotalViewCount();
}
