// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * <pre>
 * StoryBoardParams 包含故事板渲染的相关参数
 * </pre>
 *
 * Protobuf type {@code rankquantity.voyager.api.StoryBoardParams}
 */
@com.google.protobuf.Generated
public final class StoryBoardParams extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.StoryBoardParams)
    StoryBoardParamsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      StoryBoardParams.class.getName());
  }
  // Use StoryBoardParams.newBuilder() to construct.
  private StoryBoardParams(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StoryBoardParams() {
    storyDescription_ = "";
    sdModel_ = "";
    refImage_ = "";
    layoutStyle_ = "";
    style_ = "";
    negativePrompt_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_StoryBoardParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_StoryBoardParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.StoryBoardParams.class, com.rankquantity.voyager.api.StoryBoardParams.Builder.class);
  }

  public static final int BOARD_ID_FIELD_NUMBER = 1;
  private long boardId_ = 0L;
  /**
   * <pre>
   * 故事板ID
   * </pre>
   *
   * <code>int64 board_id = 1 [json_name = "boardId"];</code>
   * @return The boardId.
   */
  @java.lang.Override
  public long getBoardId() {
    return boardId_;
  }

  public static final int STORYDESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object storyDescription_ = "";
  /**
   * <pre>
   * 故事描述
   * </pre>
   *
   * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
   * @return The storyDescription.
   */
  @java.lang.Override
  public java.lang.String getStoryDescription() {
    java.lang.Object ref = storyDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      storyDescription_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事描述
   * </pre>
   *
   * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
   * @return The bytes for storyDescription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStoryDescriptionBytes() {
    java.lang.Object ref = storyDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      storyDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMIDS_FIELD_NUMBER = 3;
  private int numIds_ = 0;
  /**
   * <pre>
   * ID数量
   * </pre>
   *
   * <code>int32 NumIds = 3 [json_name = "NumIds"];</code>
   * @return The numIds.
   */
  @java.lang.Override
  public int getNumIds() {
    return numIds_;
  }

  public static final int NUMSTEPS_FIELD_NUMBER = 4;
  private int numSteps_ = 0;
  /**
   * <pre>
   * 步骤数
   * </pre>
   *
   * <code>int32 NumSteps = 4 [json_name = "NumSteps"];</code>
   * @return The numSteps.
   */
  @java.lang.Override
  public int getNumSteps() {
    return numSteps_;
  }

  public static final int SDMODEL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sdModel_ = "";
  /**
   * <pre>
   * 模型名称
   * </pre>
   *
   * <code>string SdModel = 5 [json_name = "SdModel"];</code>
   * @return The sdModel.
   */
  @java.lang.Override
  public java.lang.String getSdModel() {
    java.lang.Object ref = sdModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sdModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 模型名称
   * </pre>
   *
   * <code>string SdModel = 5 [json_name = "SdModel"];</code>
   * @return The bytes for sdModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSdModelBytes() {
    java.lang.Object ref = sdModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sdModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFIMAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object refImage_ = "";
  /**
   * <pre>
   * 参考图片
   * </pre>
   *
   * <code>string RefImage = 6 [json_name = "RefImage"];</code>
   * @return The refImage.
   */
  @java.lang.Override
  public java.lang.String getRefImage() {
    java.lang.Object ref = refImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refImage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 参考图片
   * </pre>
   *
   * <code>string RefImage = 6 [json_name = "RefImage"];</code>
   * @return The bytes for refImage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefImageBytes() {
    java.lang.Object ref = refImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAYOUTSTYLE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object layoutStyle_ = "";
  /**
   * <pre>
   * 布局风格
   * </pre>
   *
   * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
   * @return The layoutStyle.
   */
  @java.lang.Override
  public java.lang.String getLayoutStyle() {
    java.lang.Object ref = layoutStyle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      layoutStyle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 布局风格
   * </pre>
   *
   * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
   * @return The bytes for layoutStyle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLayoutStyleBytes() {
    java.lang.Object ref = layoutStyle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      layoutStyle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STYLE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object style_ = "";
  /**
   * <pre>
   * 风格
   * </pre>
   *
   * <code>string Style = 8 [json_name = "Style"];</code>
   * @return The style.
   */
  @java.lang.Override
  public java.lang.String getStyle() {
    java.lang.Object ref = style_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      style_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 风格
   * </pre>
   *
   * <code>string Style = 8 [json_name = "Style"];</code>
   * @return The bytes for style.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStyleBytes() {
    java.lang.Object ref = style_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      style_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEGATIVEPROMPT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object negativePrompt_ = "";
  /**
   * <pre>
   * 负面提示词
   * </pre>
   *
   * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
   * @return The negativePrompt.
   */
  @java.lang.Override
  public java.lang.String getNegativePrompt() {
    java.lang.Object ref = negativePrompt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      negativePrompt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 负面提示词
   * </pre>
   *
   * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
   * @return The bytes for negativePrompt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNegativePromptBytes() {
    java.lang.Object ref = negativePrompt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      negativePrompt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUTQUALITY_FIELD_NUMBER = 10;
  private int outputQuality_ = 0;
  /**
   * <pre>
   * 输出质量
   * </pre>
   *
   * <code>int32 OutputQuality = 10 [json_name = "OutputQuality"];</code>
   * @return The outputQuality.
   */
  @java.lang.Override
  public int getOutputQuality() {
    return outputQuality_;
  }

  public static final int GUIDANCESCALE_FIELD_NUMBER = 11;
  private float guidanceScale_ = 0F;
  /**
   * <pre>
   * 引导比例
   * </pre>
   *
   * <code>float GuidanceScale = 11 [json_name = "GuidanceScale"];</code>
   * @return The guidanceScale.
   */
  @java.lang.Override
  public float getGuidanceScale() {
    return guidanceScale_;
  }

  public static final int OUTPUTFORMAT_FIELD_NUMBER = 13;
  private int outputFormat_ = 0;
  /**
   * <pre>
   * 输出格式
   * </pre>
   *
   * <code>int32 OutputFormat = 13 [json_name = "OutputFormat"];</code>
   * @return The outputFormat.
   */
  @java.lang.Override
  public int getOutputFormat() {
    return outputFormat_;
  }

  public static final int IMAGEWIDTH_FIELD_NUMBER = 14;
  private int imageWidth_ = 0;
  /**
   * <pre>
   * 图片宽度
   * </pre>
   *
   * <code>int32 ImageWidth = 14 [json_name = "ImageWidth"];</code>
   * @return The imageWidth.
   */
  @java.lang.Override
  public int getImageWidth() {
    return imageWidth_;
  }

  public static final int IMAGEHEIGHT_FIELD_NUMBER = 15;
  private int imageHeight_ = 0;
  /**
   * <pre>
   * 图片高度
   * </pre>
   *
   * <code>int32 ImageHeight = 15 [json_name = "ImageHeight"];</code>
   * @return The imageHeight.
   */
  @java.lang.Override
  public int getImageHeight() {
    return imageHeight_;
  }

  public static final int SCENE_COUNT_FIELD_NUMBER = 16;
  private int sceneCount_ = 0;
  /**
   * <pre>
   * 场景数量
   * </pre>
   *
   * <code>int32 scene_count = 16 [json_name = "sceneCount"];</code>
   * @return The sceneCount.
   */
  @java.lang.Override
  public int getSceneCount() {
    return sceneCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (boardId_ != 0L) {
      output.writeInt64(1, boardId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(storyDescription_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, storyDescription_);
    }
    if (numIds_ != 0) {
      output.writeInt32(3, numIds_);
    }
    if (numSteps_ != 0) {
      output.writeInt32(4, numSteps_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sdModel_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, sdModel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(refImage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, refImage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layoutStyle_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, layoutStyle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(style_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, style_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(negativePrompt_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, negativePrompt_);
    }
    if (outputQuality_ != 0) {
      output.writeInt32(10, outputQuality_);
    }
    if (java.lang.Float.floatToRawIntBits(guidanceScale_) != 0) {
      output.writeFloat(11, guidanceScale_);
    }
    if (outputFormat_ != 0) {
      output.writeInt32(13, outputFormat_);
    }
    if (imageWidth_ != 0) {
      output.writeInt32(14, imageWidth_);
    }
    if (imageHeight_ != 0) {
      output.writeInt32(15, imageHeight_);
    }
    if (sceneCount_ != 0) {
      output.writeInt32(16, sceneCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (boardId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, boardId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(storyDescription_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, storyDescription_);
    }
    if (numIds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numIds_);
    }
    if (numSteps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numSteps_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sdModel_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sdModel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(refImage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, refImage_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layoutStyle_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, layoutStyle_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(style_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, style_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(negativePrompt_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, negativePrompt_);
    }
    if (outputQuality_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, outputQuality_);
    }
    if (java.lang.Float.floatToRawIntBits(guidanceScale_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(11, guidanceScale_);
    }
    if (outputFormat_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, outputFormat_);
    }
    if (imageWidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, imageWidth_);
    }
    if (imageHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, imageHeight_);
    }
    if (sceneCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, sceneCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.StoryBoardParams)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.StoryBoardParams other = (com.rankquantity.voyager.api.StoryBoardParams) obj;

    if (getBoardId()
        != other.getBoardId()) return false;
    if (!getStoryDescription()
        .equals(other.getStoryDescription())) return false;
    if (getNumIds()
        != other.getNumIds()) return false;
    if (getNumSteps()
        != other.getNumSteps()) return false;
    if (!getSdModel()
        .equals(other.getSdModel())) return false;
    if (!getRefImage()
        .equals(other.getRefImage())) return false;
    if (!getLayoutStyle()
        .equals(other.getLayoutStyle())) return false;
    if (!getStyle()
        .equals(other.getStyle())) return false;
    if (!getNegativePrompt()
        .equals(other.getNegativePrompt())) return false;
    if (getOutputQuality()
        != other.getOutputQuality()) return false;
    if (java.lang.Float.floatToIntBits(getGuidanceScale())
        != java.lang.Float.floatToIntBits(
            other.getGuidanceScale())) return false;
    if (getOutputFormat()
        != other.getOutputFormat()) return false;
    if (getImageWidth()
        != other.getImageWidth()) return false;
    if (getImageHeight()
        != other.getImageHeight()) return false;
    if (getSceneCount()
        != other.getSceneCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOARD_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBoardId());
    hash = (37 * hash) + STORYDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getStoryDescription().hashCode();
    hash = (37 * hash) + NUMIDS_FIELD_NUMBER;
    hash = (53 * hash) + getNumIds();
    hash = (37 * hash) + NUMSTEPS_FIELD_NUMBER;
    hash = (53 * hash) + getNumSteps();
    hash = (37 * hash) + SDMODEL_FIELD_NUMBER;
    hash = (53 * hash) + getSdModel().hashCode();
    hash = (37 * hash) + REFIMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getRefImage().hashCode();
    hash = (37 * hash) + LAYOUTSTYLE_FIELD_NUMBER;
    hash = (53 * hash) + getLayoutStyle().hashCode();
    hash = (37 * hash) + STYLE_FIELD_NUMBER;
    hash = (53 * hash) + getStyle().hashCode();
    hash = (37 * hash) + NEGATIVEPROMPT_FIELD_NUMBER;
    hash = (53 * hash) + getNegativePrompt().hashCode();
    hash = (37 * hash) + OUTPUTQUALITY_FIELD_NUMBER;
    hash = (53 * hash) + getOutputQuality();
    hash = (37 * hash) + GUIDANCESCALE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getGuidanceScale());
    hash = (37 * hash) + OUTPUTFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getOutputFormat();
    hash = (37 * hash) + IMAGEWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getImageWidth();
    hash = (37 * hash) + IMAGEHEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getImageHeight();
    hash = (37 * hash) + SCENE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSceneCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.StoryBoardParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.StoryBoardParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.StoryBoardParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.StoryBoardParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * StoryBoardParams 包含故事板渲染的相关参数
   * </pre>
   *
   * Protobuf type {@code rankquantity.voyager.api.StoryBoardParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.StoryBoardParams)
      com.rankquantity.voyager.api.StoryBoardParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_StoryBoardParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_StoryBoardParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.StoryBoardParams.class, com.rankquantity.voyager.api.StoryBoardParams.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.StoryBoardParams.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      boardId_ = 0L;
      storyDescription_ = "";
      numIds_ = 0;
      numSteps_ = 0;
      sdModel_ = "";
      refImage_ = "";
      layoutStyle_ = "";
      style_ = "";
      negativePrompt_ = "";
      outputQuality_ = 0;
      guidanceScale_ = 0F;
      outputFormat_ = 0;
      imageWidth_ = 0;
      imageHeight_ = 0;
      sceneCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_StoryBoardParams_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryBoardParams getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryBoardParams build() {
      com.rankquantity.voyager.api.StoryBoardParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryBoardParams buildPartial() {
      com.rankquantity.voyager.api.StoryBoardParams result = new com.rankquantity.voyager.api.StoryBoardParams(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.StoryBoardParams result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.boardId_ = boardId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.storyDescription_ = storyDescription_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.numIds_ = numIds_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.numSteps_ = numSteps_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sdModel_ = sdModel_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.refImage_ = refImage_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.layoutStyle_ = layoutStyle_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.style_ = style_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.negativePrompt_ = negativePrompt_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.outputQuality_ = outputQuality_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.guidanceScale_ = guidanceScale_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.outputFormat_ = outputFormat_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.imageWidth_ = imageWidth_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.imageHeight_ = imageHeight_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.sceneCount_ = sceneCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.StoryBoardParams) {
        return mergeFrom((com.rankquantity.voyager.api.StoryBoardParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.StoryBoardParams other) {
      if (other == com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance()) return this;
      if (other.getBoardId() != 0L) {
        setBoardId(other.getBoardId());
      }
      if (!other.getStoryDescription().isEmpty()) {
        storyDescription_ = other.storyDescription_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getNumIds() != 0) {
        setNumIds(other.getNumIds());
      }
      if (other.getNumSteps() != 0) {
        setNumSteps(other.getNumSteps());
      }
      if (!other.getSdModel().isEmpty()) {
        sdModel_ = other.sdModel_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getRefImage().isEmpty()) {
        refImage_ = other.refImage_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getLayoutStyle().isEmpty()) {
        layoutStyle_ = other.layoutStyle_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getStyle().isEmpty()) {
        style_ = other.style_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getNegativePrompt().isEmpty()) {
        negativePrompt_ = other.negativePrompt_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getOutputQuality() != 0) {
        setOutputQuality(other.getOutputQuality());
      }
      if (java.lang.Float.floatToRawIntBits(other.getGuidanceScale()) != 0) {
        setGuidanceScale(other.getGuidanceScale());
      }
      if (other.getOutputFormat() != 0) {
        setOutputFormat(other.getOutputFormat());
      }
      if (other.getImageWidth() != 0) {
        setImageWidth(other.getImageWidth());
      }
      if (other.getImageHeight() != 0) {
        setImageHeight(other.getImageHeight());
      }
      if (other.getSceneCount() != 0) {
        setSceneCount(other.getSceneCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              boardId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              storyDescription_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              numIds_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              numSteps_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              sdModel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              refImage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              layoutStyle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              style_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              negativePrompt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              outputQuality_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 93: {
              guidanceScale_ = input.readFloat();
              bitField0_ |= 0x00000400;
              break;
            } // case 93
            case 104: {
              outputFormat_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 104
            case 112: {
              imageWidth_ = input.readInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 112
            case 120: {
              imageHeight_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 120
            case 128: {
              sceneCount_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long boardId_ ;
    /**
     * <pre>
     * 故事板ID
     * </pre>
     *
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @return The boardId.
     */
    @java.lang.Override
    public long getBoardId() {
      return boardId_;
    }
    /**
     * <pre>
     * 故事板ID
     * </pre>
     *
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @param value The boardId to set.
     * @return This builder for chaining.
     */
    public Builder setBoardId(long value) {

      boardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板ID
     * </pre>
     *
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoardId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      boardId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object storyDescription_ = "";
    /**
     * <pre>
     * 故事描述
     * </pre>
     *
     * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
     * @return The storyDescription.
     */
    public java.lang.String getStoryDescription() {
      java.lang.Object ref = storyDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storyDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事描述
     * </pre>
     *
     * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
     * @return The bytes for storyDescription.
     */
    public com.google.protobuf.ByteString
        getStoryDescriptionBytes() {
      java.lang.Object ref = storyDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storyDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事描述
     * </pre>
     *
     * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
     * @param value The storyDescription to set.
     * @return This builder for chaining.
     */
    public Builder setStoryDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      storyDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事描述
     * </pre>
     *
     * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoryDescription() {
      storyDescription_ = getDefaultInstance().getStoryDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事描述
     * </pre>
     *
     * <code>string StoryDescription = 2 [json_name = "StoryDescription"];</code>
     * @param value The bytes for storyDescription to set.
     * @return This builder for chaining.
     */
    public Builder setStoryDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      storyDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int numIds_ ;
    /**
     * <pre>
     * ID数量
     * </pre>
     *
     * <code>int32 NumIds = 3 [json_name = "NumIds"];</code>
     * @return The numIds.
     */
    @java.lang.Override
    public int getNumIds() {
      return numIds_;
    }
    /**
     * <pre>
     * ID数量
     * </pre>
     *
     * <code>int32 NumIds = 3 [json_name = "NumIds"];</code>
     * @param value The numIds to set.
     * @return This builder for chaining.
     */
    public Builder setNumIds(int value) {

      numIds_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID数量
     * </pre>
     *
     * <code>int32 NumIds = 3 [json_name = "NumIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumIds() {
      bitField0_ = (bitField0_ & ~0x00000004);
      numIds_ = 0;
      onChanged();
      return this;
    }

    private int numSteps_ ;
    /**
     * <pre>
     * 步骤数
     * </pre>
     *
     * <code>int32 NumSteps = 4 [json_name = "NumSteps"];</code>
     * @return The numSteps.
     */
    @java.lang.Override
    public int getNumSteps() {
      return numSteps_;
    }
    /**
     * <pre>
     * 步骤数
     * </pre>
     *
     * <code>int32 NumSteps = 4 [json_name = "NumSteps"];</code>
     * @param value The numSteps to set.
     * @return This builder for chaining.
     */
    public Builder setNumSteps(int value) {

      numSteps_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 步骤数
     * </pre>
     *
     * <code>int32 NumSteps = 4 [json_name = "NumSteps"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumSteps() {
      bitField0_ = (bitField0_ & ~0x00000008);
      numSteps_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sdModel_ = "";
    /**
     * <pre>
     * 模型名称
     * </pre>
     *
     * <code>string SdModel = 5 [json_name = "SdModel"];</code>
     * @return The sdModel.
     */
    public java.lang.String getSdModel() {
      java.lang.Object ref = sdModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 模型名称
     * </pre>
     *
     * <code>string SdModel = 5 [json_name = "SdModel"];</code>
     * @return The bytes for sdModel.
     */
    public com.google.protobuf.ByteString
        getSdModelBytes() {
      java.lang.Object ref = sdModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 模型名称
     * </pre>
     *
     * <code>string SdModel = 5 [json_name = "SdModel"];</code>
     * @param value The sdModel to set.
     * @return This builder for chaining.
     */
    public Builder setSdModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sdModel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模型名称
     * </pre>
     *
     * <code>string SdModel = 5 [json_name = "SdModel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSdModel() {
      sdModel_ = getDefaultInstance().getSdModel();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模型名称
     * </pre>
     *
     * <code>string SdModel = 5 [json_name = "SdModel"];</code>
     * @param value The bytes for sdModel to set.
     * @return This builder for chaining.
     */
    public Builder setSdModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sdModel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object refImage_ = "";
    /**
     * <pre>
     * 参考图片
     * </pre>
     *
     * <code>string RefImage = 6 [json_name = "RefImage"];</code>
     * @return The refImage.
     */
    public java.lang.String getRefImage() {
      java.lang.Object ref = refImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 参考图片
     * </pre>
     *
     * <code>string RefImage = 6 [json_name = "RefImage"];</code>
     * @return The bytes for refImage.
     */
    public com.google.protobuf.ByteString
        getRefImageBytes() {
      java.lang.Object ref = refImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 参考图片
     * </pre>
     *
     * <code>string RefImage = 6 [json_name = "RefImage"];</code>
     * @param value The refImage to set.
     * @return This builder for chaining.
     */
    public Builder setRefImage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      refImage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考图片
     * </pre>
     *
     * <code>string RefImage = 6 [json_name = "RefImage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefImage() {
      refImage_ = getDefaultInstance().getRefImage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考图片
     * </pre>
     *
     * <code>string RefImage = 6 [json_name = "RefImage"];</code>
     * @param value The bytes for refImage to set.
     * @return This builder for chaining.
     */
    public Builder setRefImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      refImage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object layoutStyle_ = "";
    /**
     * <pre>
     * 布局风格
     * </pre>
     *
     * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
     * @return The layoutStyle.
     */
    public java.lang.String getLayoutStyle() {
      java.lang.Object ref = layoutStyle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        layoutStyle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 布局风格
     * </pre>
     *
     * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
     * @return The bytes for layoutStyle.
     */
    public com.google.protobuf.ByteString
        getLayoutStyleBytes() {
      java.lang.Object ref = layoutStyle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        layoutStyle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 布局风格
     * </pre>
     *
     * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
     * @param value The layoutStyle to set.
     * @return This builder for chaining.
     */
    public Builder setLayoutStyle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      layoutStyle_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 布局风格
     * </pre>
     *
     * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLayoutStyle() {
      layoutStyle_ = getDefaultInstance().getLayoutStyle();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 布局风格
     * </pre>
     *
     * <code>string LayoutStyle = 7 [json_name = "LayoutStyle"];</code>
     * @param value The bytes for layoutStyle to set.
     * @return This builder for chaining.
     */
    public Builder setLayoutStyleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      layoutStyle_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object style_ = "";
    /**
     * <pre>
     * 风格
     * </pre>
     *
     * <code>string Style = 8 [json_name = "Style"];</code>
     * @return The style.
     */
    public java.lang.String getStyle() {
      java.lang.Object ref = style_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        style_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 风格
     * </pre>
     *
     * <code>string Style = 8 [json_name = "Style"];</code>
     * @return The bytes for style.
     */
    public com.google.protobuf.ByteString
        getStyleBytes() {
      java.lang.Object ref = style_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        style_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 风格
     * </pre>
     *
     * <code>string Style = 8 [json_name = "Style"];</code>
     * @param value The style to set.
     * @return This builder for chaining.
     */
    public Builder setStyle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      style_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 风格
     * </pre>
     *
     * <code>string Style = 8 [json_name = "Style"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStyle() {
      style_ = getDefaultInstance().getStyle();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 风格
     * </pre>
     *
     * <code>string Style = 8 [json_name = "Style"];</code>
     * @param value The bytes for style to set.
     * @return This builder for chaining.
     */
    public Builder setStyleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      style_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object negativePrompt_ = "";
    /**
     * <pre>
     * 负面提示词
     * </pre>
     *
     * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
     * @return The negativePrompt.
     */
    public java.lang.String getNegativePrompt() {
      java.lang.Object ref = negativePrompt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negativePrompt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 负面提示词
     * </pre>
     *
     * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
     * @return The bytes for negativePrompt.
     */
    public com.google.protobuf.ByteString
        getNegativePromptBytes() {
      java.lang.Object ref = negativePrompt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negativePrompt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 负面提示词
     * </pre>
     *
     * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
     * @param value The negativePrompt to set.
     * @return This builder for chaining.
     */
    public Builder setNegativePrompt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      negativePrompt_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 负面提示词
     * </pre>
     *
     * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNegativePrompt() {
      negativePrompt_ = getDefaultInstance().getNegativePrompt();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 负面提示词
     * </pre>
     *
     * <code>string NegativePrompt = 9 [json_name = "NegativePrompt"];</code>
     * @param value The bytes for negativePrompt to set.
     * @return This builder for chaining.
     */
    public Builder setNegativePromptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      negativePrompt_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private int outputQuality_ ;
    /**
     * <pre>
     * 输出质量
     * </pre>
     *
     * <code>int32 OutputQuality = 10 [json_name = "OutputQuality"];</code>
     * @return The outputQuality.
     */
    @java.lang.Override
    public int getOutputQuality() {
      return outputQuality_;
    }
    /**
     * <pre>
     * 输出质量
     * </pre>
     *
     * <code>int32 OutputQuality = 10 [json_name = "OutputQuality"];</code>
     * @param value The outputQuality to set.
     * @return This builder for chaining.
     */
    public Builder setOutputQuality(int value) {

      outputQuality_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出质量
     * </pre>
     *
     * <code>int32 OutputQuality = 10 [json_name = "OutputQuality"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputQuality() {
      bitField0_ = (bitField0_ & ~0x00000200);
      outputQuality_ = 0;
      onChanged();
      return this;
    }

    private float guidanceScale_ ;
    /**
     * <pre>
     * 引导比例
     * </pre>
     *
     * <code>float GuidanceScale = 11 [json_name = "GuidanceScale"];</code>
     * @return The guidanceScale.
     */
    @java.lang.Override
    public float getGuidanceScale() {
      return guidanceScale_;
    }
    /**
     * <pre>
     * 引导比例
     * </pre>
     *
     * <code>float GuidanceScale = 11 [json_name = "GuidanceScale"];</code>
     * @param value The guidanceScale to set.
     * @return This builder for chaining.
     */
    public Builder setGuidanceScale(float value) {

      guidanceScale_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引导比例
     * </pre>
     *
     * <code>float GuidanceScale = 11 [json_name = "GuidanceScale"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGuidanceScale() {
      bitField0_ = (bitField0_ & ~0x00000400);
      guidanceScale_ = 0F;
      onChanged();
      return this;
    }

    private int outputFormat_ ;
    /**
     * <pre>
     * 输出格式
     * </pre>
     *
     * <code>int32 OutputFormat = 13 [json_name = "OutputFormat"];</code>
     * @return The outputFormat.
     */
    @java.lang.Override
    public int getOutputFormat() {
      return outputFormat_;
    }
    /**
     * <pre>
     * 输出格式
     * </pre>
     *
     * <code>int32 OutputFormat = 13 [json_name = "OutputFormat"];</code>
     * @param value The outputFormat to set.
     * @return This builder for chaining.
     */
    public Builder setOutputFormat(int value) {

      outputFormat_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出格式
     * </pre>
     *
     * <code>int32 OutputFormat = 13 [json_name = "OutputFormat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputFormat() {
      bitField0_ = (bitField0_ & ~0x00000800);
      outputFormat_ = 0;
      onChanged();
      return this;
    }

    private int imageWidth_ ;
    /**
     * <pre>
     * 图片宽度
     * </pre>
     *
     * <code>int32 ImageWidth = 14 [json_name = "ImageWidth"];</code>
     * @return The imageWidth.
     */
    @java.lang.Override
    public int getImageWidth() {
      return imageWidth_;
    }
    /**
     * <pre>
     * 图片宽度
     * </pre>
     *
     * <code>int32 ImageWidth = 14 [json_name = "ImageWidth"];</code>
     * @param value The imageWidth to set.
     * @return This builder for chaining.
     */
    public Builder setImageWidth(int value) {

      imageWidth_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 图片宽度
     * </pre>
     *
     * <code>int32 ImageWidth = 14 [json_name = "ImageWidth"];</code>
     * @return This builder for chaining.
     */
    public Builder clearImageWidth() {
      bitField0_ = (bitField0_ & ~0x00001000);
      imageWidth_ = 0;
      onChanged();
      return this;
    }

    private int imageHeight_ ;
    /**
     * <pre>
     * 图片高度
     * </pre>
     *
     * <code>int32 ImageHeight = 15 [json_name = "ImageHeight"];</code>
     * @return The imageHeight.
     */
    @java.lang.Override
    public int getImageHeight() {
      return imageHeight_;
    }
    /**
     * <pre>
     * 图片高度
     * </pre>
     *
     * <code>int32 ImageHeight = 15 [json_name = "ImageHeight"];</code>
     * @param value The imageHeight to set.
     * @return This builder for chaining.
     */
    public Builder setImageHeight(int value) {

      imageHeight_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 图片高度
     * </pre>
     *
     * <code>int32 ImageHeight = 15 [json_name = "ImageHeight"];</code>
     * @return This builder for chaining.
     */
    public Builder clearImageHeight() {
      bitField0_ = (bitField0_ & ~0x00002000);
      imageHeight_ = 0;
      onChanged();
      return this;
    }

    private int sceneCount_ ;
    /**
     * <pre>
     * 场景数量
     * </pre>
     *
     * <code>int32 scene_count = 16 [json_name = "sceneCount"];</code>
     * @return The sceneCount.
     */
    @java.lang.Override
    public int getSceneCount() {
      return sceneCount_;
    }
    /**
     * <pre>
     * 场景数量
     * </pre>
     *
     * <code>int32 scene_count = 16 [json_name = "sceneCount"];</code>
     * @param value The sceneCount to set.
     * @return This builder for chaining.
     */
    public Builder setSceneCount(int value) {

      sceneCount_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 场景数量
     * </pre>
     *
     * <code>int32 scene_count = 16 [json_name = "sceneCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSceneCount() {
      bitField0_ = (bitField0_ & ~0x00004000);
      sceneCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.StoryBoardParams)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.StoryBoardParams)
  private static final com.rankquantity.voyager.api.StoryBoardParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.StoryBoardParams();
  }

  public static com.rankquantity.voyager.api.StoryBoardParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StoryBoardParams>
      PARSER = new com.google.protobuf.AbstractParser<StoryBoardParams>() {
    @java.lang.Override
    public StoryBoardParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StoryBoardParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StoryBoardParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.StoryBoardParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

