// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface StoryBoardActiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.StoryBoardActive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 故事板信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoard storyboard = 1 [json_name = "storyboard"];</code>
   * @return Whether the storyboard field is set.
   */
  boolean hasStoryboard();
  /**
   * <pre>
   * 故事板信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoard storyboard = 1 [json_name = "storyboard"];</code>
   * @return The storyboard.
   */
  com.rankquantity.voyager.api.StoryBoard getStoryboard();
  /**
   * <pre>
   * 故事板信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoard storyboard = 1 [json_name = "storyboard"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardOrBuilder getStoryboardOrBuilder();

  /**
   * <pre>
   * 总点赞数
   * </pre>
   *
   * <code>int64 total_like_count = 2 [json_name = "totalLikeCount"];</code>
   * @return The totalLikeCount.
   */
  long getTotalLikeCount();

  /**
   * <pre>
   * 总评论数
   * </pre>
   *
   * <code>int64 total_comment_count = 3 [json_name = "totalCommentCount"];</code>
   * @return The totalCommentCount.
   */
  long getTotalCommentCount();

  /**
   * <pre>
   * 总分享数
   * </pre>
   *
   * <code>int64 total_share_count = 4 [json_name = "totalShareCount"];</code>
   * @return The totalShareCount.
   */
  long getTotalShareCount();

  /**
   * <pre>
   * 总渲染数
   * </pre>
   *
   * <code>int64 total_render_count = 5 [json_name = "totalRenderCount"];</code>
   * @return The totalRenderCount.
   */
  long getTotalRenderCount();

  /**
   * <pre>
   * 总分叉数
   * </pre>
   *
   * <code>int64 total_fork_count = 6 [json_name = "totalForkCount"];</code>
   * @return The totalForkCount.
   */
  long getTotalForkCount();

  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveUser users = 7 [json_name = "users"];</code>
   */
  java.util.List<com.rankquantity.voyager.api.StoryBoardActiveUser> 
      getUsersList();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveUser users = 7 [json_name = "users"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardActiveUser getUsers(int index);
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveUser users = 7 [json_name = "users"];</code>
   */
  int getUsersCount();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveUser users = 7 [json_name = "users"];</code>
   */
  java.util.List<? extends com.rankquantity.voyager.api.StoryBoardActiveUserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveUser users = 7 [json_name = "users"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardActiveUserOrBuilder getUsersOrBuilder(
      int index);

  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveRole roles = 8 [json_name = "roles"];</code>
   */
  java.util.List<com.rankquantity.voyager.api.StoryBoardActiveRole> 
      getRolesList();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveRole roles = 8 [json_name = "roles"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardActiveRole getRoles(int index);
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveRole roles = 8 [json_name = "roles"];</code>
   */
  int getRolesCount();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveRole roles = 8 [json_name = "roles"];</code>
   */
  java.util.List<? extends com.rankquantity.voyager.api.StoryBoardActiveRoleOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryBoardActiveRole roles = 8 [json_name = "roles"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardActiveRoleOrBuilder getRolesOrBuilder(
      int index);

  /**
   * <pre>
   * 创建者信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardActiveUser creator = 9 [json_name = "creator"];</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <pre>
   * 创建者信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardActiveUser creator = 9 [json_name = "creator"];</code>
   * @return The creator.
   */
  com.rankquantity.voyager.api.StoryBoardActiveUser getCreator();
  /**
   * <pre>
   * 创建者信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardActiveUser creator = 9 [json_name = "creator"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardActiveUserOrBuilder getCreatorOrBuilder();

  /**
   * <pre>
   * 摘要信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StorySummaryInfo summary = 10 [json_name = "summary"];</code>
   * @return Whether the summary field is set.
   */
  boolean hasSummary();
  /**
   * <pre>
   * 摘要信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StorySummaryInfo summary = 10 [json_name = "summary"];</code>
   * @return The summary.
   */
  com.rankquantity.voyager.api.StorySummaryInfo getSummary();
  /**
   * <pre>
   * 摘要信息
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StorySummaryInfo summary = 10 [json_name = "summary"];</code>
   */
  com.rankquantity.voyager.api.StorySummaryInfoOrBuilder getSummaryOrBuilder();

  /**
   * <pre>
   * 是否点赞
   * </pre>
   *
   * <code>bool isliked = 11 [json_name = "isliked"];</code>
   * @return The isliked.
   */
  boolean getIsliked();

  /**
   * <pre>
   * 修改时间
   * </pre>
   *
   * <code>int64 mtime = 12 [json_name = "mtime"];</code>
   * @return The mtime.
   */
  long getMtime();
}
