// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: error.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * <pre>
 * 故事板相关错误描述
 * </pre>
 *
 * Protobuf type {@code rankquantity.voyager.api.StoryboardErrorMessages}
 */
@com.google.protobuf.Generated
public final class StoryboardErrorMessages extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.StoryboardErrorMessages)
    StoryboardErrorMessagesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      StoryboardErrorMessages.class.getName());
  }
  // Use StoryboardErrorMessages.newBuilder() to construct.
  private StoryboardErrorMessages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StoryboardErrorMessages() {
    sTORYBOARDNOTFOUND_ = "";
    sTORYBOARDALREADYEXISTS_ = "";
    sTORYBOARDPERMISSIONDENIED_ = "";
    sTORYBOARDRENDERERROR_ = "";
    sTORYBOARDLOCKED_ = "";
    sTORYBOARDSTATUSERROR_ = "";
    sTORYBOARDVERSIONERROR_ = "";
    sTORYBOARDSCENEERROR_ = "";
    sTORYBOARDGENERATIONFAILED_ = "";
    sTORYBOARDOPERATIONDENIED_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_StoryboardErrorMessages_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_StoryboardErrorMessages_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.StoryboardErrorMessages.class, com.rankquantity.voyager.api.StoryboardErrorMessages.Builder.class);
  }

  public static final int STORYBOARD_NOT_FOUND_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDNOTFOUND_ = "";
  /**
   * <pre>
   * 故事板不存在
   * </pre>
   *
   * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
   * @return The sTORYBOARDNOTFOUND.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDNOTFOUND() {
    java.lang.Object ref = sTORYBOARDNOTFOUND_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDNOTFOUND_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板不存在
   * </pre>
   *
   * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
   * @return The bytes for sTORYBOARDNOTFOUND.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDNOTFOUNDBytes() {
    java.lang.Object ref = sTORYBOARDNOTFOUND_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDNOTFOUND_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_ALREADY_EXISTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDALREADYEXISTS_ = "";
  /**
   * <pre>
   * 故事板已存在
   * </pre>
   *
   * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
   * @return The sTORYBOARDALREADYEXISTS.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDALREADYEXISTS() {
    java.lang.Object ref = sTORYBOARDALREADYEXISTS_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDALREADYEXISTS_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板已存在
   * </pre>
   *
   * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
   * @return The bytes for sTORYBOARDALREADYEXISTS.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDALREADYEXISTSBytes() {
    java.lang.Object ref = sTORYBOARDALREADYEXISTS_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDALREADYEXISTS_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_PERMISSION_DENIED_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDPERMISSIONDENIED_ = "";
  /**
   * <pre>
   * 故事板权限不足
   * </pre>
   *
   * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
   * @return The sTORYBOARDPERMISSIONDENIED.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDPERMISSIONDENIED() {
    java.lang.Object ref = sTORYBOARDPERMISSIONDENIED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDPERMISSIONDENIED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板权限不足
   * </pre>
   *
   * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
   * @return The bytes for sTORYBOARDPERMISSIONDENIED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDPERMISSIONDENIEDBytes() {
    java.lang.Object ref = sTORYBOARDPERMISSIONDENIED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDPERMISSIONDENIED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_RENDER_ERROR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDRENDERERROR_ = "";
  /**
   * <pre>
   * 故事板渲染错误
   * </pre>
   *
   * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
   * @return The sTORYBOARDRENDERERROR.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDRENDERERROR() {
    java.lang.Object ref = sTORYBOARDRENDERERROR_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDRENDERERROR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板渲染错误
   * </pre>
   *
   * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
   * @return The bytes for sTORYBOARDRENDERERROR.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDRENDERERRORBytes() {
    java.lang.Object ref = sTORYBOARDRENDERERROR_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDRENDERERROR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_LOCKED_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDLOCKED_ = "";
  /**
   * <pre>
   * 故事板已锁定
   * </pre>
   *
   * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
   * @return The sTORYBOARDLOCKED.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDLOCKED() {
    java.lang.Object ref = sTORYBOARDLOCKED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDLOCKED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板已锁定
   * </pre>
   *
   * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
   * @return The bytes for sTORYBOARDLOCKED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDLOCKEDBytes() {
    java.lang.Object ref = sTORYBOARDLOCKED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDLOCKED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_STATUS_ERROR_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDSTATUSERROR_ = "";
  /**
   * <pre>
   * 故事板状态错误
   * </pre>
   *
   * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
   * @return The sTORYBOARDSTATUSERROR.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDSTATUSERROR() {
    java.lang.Object ref = sTORYBOARDSTATUSERROR_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDSTATUSERROR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板状态错误
   * </pre>
   *
   * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
   * @return The bytes for sTORYBOARDSTATUSERROR.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDSTATUSERRORBytes() {
    java.lang.Object ref = sTORYBOARDSTATUSERROR_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDSTATUSERROR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_VERSION_ERROR_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDVERSIONERROR_ = "";
  /**
   * <pre>
   * 故事板版本错误
   * </pre>
   *
   * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
   * @return The sTORYBOARDVERSIONERROR.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDVERSIONERROR() {
    java.lang.Object ref = sTORYBOARDVERSIONERROR_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDVERSIONERROR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板版本错误
   * </pre>
   *
   * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
   * @return The bytes for sTORYBOARDVERSIONERROR.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDVERSIONERRORBytes() {
    java.lang.Object ref = sTORYBOARDVERSIONERROR_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDVERSIONERROR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_SCENE_ERROR_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDSCENEERROR_ = "";
  /**
   * <pre>
   * 故事板场景错误
   * </pre>
   *
   * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
   * @return The sTORYBOARDSCENEERROR.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDSCENEERROR() {
    java.lang.Object ref = sTORYBOARDSCENEERROR_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDSCENEERROR_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板场景错误
   * </pre>
   *
   * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
   * @return The bytes for sTORYBOARDSCENEERROR.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDSCENEERRORBytes() {
    java.lang.Object ref = sTORYBOARDSCENEERROR_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDSCENEERROR_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_GENERATION_FAILED_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDGENERATIONFAILED_ = "";
  /**
   * <pre>
   * 故事板生成失败
   * </pre>
   *
   * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
   * @return The sTORYBOARDGENERATIONFAILED.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDGENERATIONFAILED() {
    java.lang.Object ref = sTORYBOARDGENERATIONFAILED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDGENERATIONFAILED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板生成失败
   * </pre>
   *
   * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
   * @return The bytes for sTORYBOARDGENERATIONFAILED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDGENERATIONFAILEDBytes() {
    java.lang.Object ref = sTORYBOARDGENERATIONFAILED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDGENERATIONFAILED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STORYBOARD_OPERATION_DENIED_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sTORYBOARDOPERATIONDENIED_ = "";
  /**
   * <pre>
   * 故事板操作被拒绝
   * </pre>
   *
   * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
   * @return The sTORYBOARDOPERATIONDENIED.
   */
  @java.lang.Override
  public java.lang.String getSTORYBOARDOPERATIONDENIED() {
    java.lang.Object ref = sTORYBOARDOPERATIONDENIED_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sTORYBOARDOPERATIONDENIED_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 故事板操作被拒绝
   * </pre>
   *
   * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
   * @return The bytes for sTORYBOARDOPERATIONDENIED.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSTORYBOARDOPERATIONDENIEDBytes() {
    java.lang.Object ref = sTORYBOARDOPERATIONDENIED_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sTORYBOARDOPERATIONDENIED_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDNOTFOUND_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sTORYBOARDNOTFOUND_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDALREADYEXISTS_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sTORYBOARDALREADYEXISTS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDPERMISSIONDENIED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sTORYBOARDPERMISSIONDENIED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDRENDERERROR_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, sTORYBOARDRENDERERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDLOCKED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, sTORYBOARDLOCKED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDSTATUSERROR_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, sTORYBOARDSTATUSERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDVERSIONERROR_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, sTORYBOARDVERSIONERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDSCENEERROR_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, sTORYBOARDSCENEERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDGENERATIONFAILED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, sTORYBOARDGENERATIONFAILED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDOPERATIONDENIED_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, sTORYBOARDOPERATIONDENIED_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDNOTFOUND_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sTORYBOARDNOTFOUND_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDALREADYEXISTS_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sTORYBOARDALREADYEXISTS_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDPERMISSIONDENIED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, sTORYBOARDPERMISSIONDENIED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDRENDERERROR_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sTORYBOARDRENDERERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDLOCKED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sTORYBOARDLOCKED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDSTATUSERROR_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, sTORYBOARDSTATUSERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDVERSIONERROR_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, sTORYBOARDVERSIONERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDSCENEERROR_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, sTORYBOARDSCENEERROR_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDGENERATIONFAILED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, sTORYBOARDGENERATIONFAILED_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sTORYBOARDOPERATIONDENIED_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, sTORYBOARDOPERATIONDENIED_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.StoryboardErrorMessages)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.StoryboardErrorMessages other = (com.rankquantity.voyager.api.StoryboardErrorMessages) obj;

    if (!getSTORYBOARDNOTFOUND()
        .equals(other.getSTORYBOARDNOTFOUND())) return false;
    if (!getSTORYBOARDALREADYEXISTS()
        .equals(other.getSTORYBOARDALREADYEXISTS())) return false;
    if (!getSTORYBOARDPERMISSIONDENIED()
        .equals(other.getSTORYBOARDPERMISSIONDENIED())) return false;
    if (!getSTORYBOARDRENDERERROR()
        .equals(other.getSTORYBOARDRENDERERROR())) return false;
    if (!getSTORYBOARDLOCKED()
        .equals(other.getSTORYBOARDLOCKED())) return false;
    if (!getSTORYBOARDSTATUSERROR()
        .equals(other.getSTORYBOARDSTATUSERROR())) return false;
    if (!getSTORYBOARDVERSIONERROR()
        .equals(other.getSTORYBOARDVERSIONERROR())) return false;
    if (!getSTORYBOARDSCENEERROR()
        .equals(other.getSTORYBOARDSCENEERROR())) return false;
    if (!getSTORYBOARDGENERATIONFAILED()
        .equals(other.getSTORYBOARDGENERATIONFAILED())) return false;
    if (!getSTORYBOARDOPERATIONDENIED()
        .equals(other.getSTORYBOARDOPERATIONDENIED())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORYBOARD_NOT_FOUND_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDNOTFOUND().hashCode();
    hash = (37 * hash) + STORYBOARD_ALREADY_EXISTS_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDALREADYEXISTS().hashCode();
    hash = (37 * hash) + STORYBOARD_PERMISSION_DENIED_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDPERMISSIONDENIED().hashCode();
    hash = (37 * hash) + STORYBOARD_RENDER_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDRENDERERROR().hashCode();
    hash = (37 * hash) + STORYBOARD_LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDLOCKED().hashCode();
    hash = (37 * hash) + STORYBOARD_STATUS_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDSTATUSERROR().hashCode();
    hash = (37 * hash) + STORYBOARD_VERSION_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDVERSIONERROR().hashCode();
    hash = (37 * hash) + STORYBOARD_SCENE_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDSCENEERROR().hashCode();
    hash = (37 * hash) + STORYBOARD_GENERATION_FAILED_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDGENERATIONFAILED().hashCode();
    hash = (37 * hash) + STORYBOARD_OPERATION_DENIED_FIELD_NUMBER;
    hash = (53 * hash) + getSTORYBOARDOPERATIONDENIED().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.StoryboardErrorMessages parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.StoryboardErrorMessages prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 故事板相关错误描述
   * </pre>
   *
   * Protobuf type {@code rankquantity.voyager.api.StoryboardErrorMessages}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.StoryboardErrorMessages)
      com.rankquantity.voyager.api.StoryboardErrorMessagesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_StoryboardErrorMessages_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_StoryboardErrorMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.StoryboardErrorMessages.class, com.rankquantity.voyager.api.StoryboardErrorMessages.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.StoryboardErrorMessages.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sTORYBOARDNOTFOUND_ = "";
      sTORYBOARDALREADYEXISTS_ = "";
      sTORYBOARDPERMISSIONDENIED_ = "";
      sTORYBOARDRENDERERROR_ = "";
      sTORYBOARDLOCKED_ = "";
      sTORYBOARDSTATUSERROR_ = "";
      sTORYBOARDVERSIONERROR_ = "";
      sTORYBOARDSCENEERROR_ = "";
      sTORYBOARDGENERATIONFAILED_ = "";
      sTORYBOARDOPERATIONDENIED_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.ErrorProto.internal_static_rankquantity_voyager_api_StoryboardErrorMessages_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryboardErrorMessages getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.StoryboardErrorMessages.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryboardErrorMessages build() {
      com.rankquantity.voyager.api.StoryboardErrorMessages result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.StoryboardErrorMessages buildPartial() {
      com.rankquantity.voyager.api.StoryboardErrorMessages result = new com.rankquantity.voyager.api.StoryboardErrorMessages(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.StoryboardErrorMessages result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sTORYBOARDNOTFOUND_ = sTORYBOARDNOTFOUND_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sTORYBOARDALREADYEXISTS_ = sTORYBOARDALREADYEXISTS_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sTORYBOARDPERMISSIONDENIED_ = sTORYBOARDPERMISSIONDENIED_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sTORYBOARDRENDERERROR_ = sTORYBOARDRENDERERROR_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sTORYBOARDLOCKED_ = sTORYBOARDLOCKED_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.sTORYBOARDSTATUSERROR_ = sTORYBOARDSTATUSERROR_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.sTORYBOARDVERSIONERROR_ = sTORYBOARDVERSIONERROR_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sTORYBOARDSCENEERROR_ = sTORYBOARDSCENEERROR_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.sTORYBOARDGENERATIONFAILED_ = sTORYBOARDGENERATIONFAILED_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.sTORYBOARDOPERATIONDENIED_ = sTORYBOARDOPERATIONDENIED_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.StoryboardErrorMessages) {
        return mergeFrom((com.rankquantity.voyager.api.StoryboardErrorMessages)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.StoryboardErrorMessages other) {
      if (other == com.rankquantity.voyager.api.StoryboardErrorMessages.getDefaultInstance()) return this;
      if (!other.getSTORYBOARDNOTFOUND().isEmpty()) {
        sTORYBOARDNOTFOUND_ = other.sTORYBOARDNOTFOUND_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSTORYBOARDALREADYEXISTS().isEmpty()) {
        sTORYBOARDALREADYEXISTS_ = other.sTORYBOARDALREADYEXISTS_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSTORYBOARDPERMISSIONDENIED().isEmpty()) {
        sTORYBOARDPERMISSIONDENIED_ = other.sTORYBOARDPERMISSIONDENIED_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSTORYBOARDRENDERERROR().isEmpty()) {
        sTORYBOARDRENDERERROR_ = other.sTORYBOARDRENDERERROR_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSTORYBOARDLOCKED().isEmpty()) {
        sTORYBOARDLOCKED_ = other.sTORYBOARDLOCKED_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSTORYBOARDSTATUSERROR().isEmpty()) {
        sTORYBOARDSTATUSERROR_ = other.sTORYBOARDSTATUSERROR_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getSTORYBOARDVERSIONERROR().isEmpty()) {
        sTORYBOARDVERSIONERROR_ = other.sTORYBOARDVERSIONERROR_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getSTORYBOARDSCENEERROR().isEmpty()) {
        sTORYBOARDSCENEERROR_ = other.sTORYBOARDSCENEERROR_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getSTORYBOARDGENERATIONFAILED().isEmpty()) {
        sTORYBOARDGENERATIONFAILED_ = other.sTORYBOARDGENERATIONFAILED_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getSTORYBOARDOPERATIONDENIED().isEmpty()) {
        sTORYBOARDOPERATIONDENIED_ = other.sTORYBOARDOPERATIONDENIED_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sTORYBOARDNOTFOUND_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sTORYBOARDALREADYEXISTS_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sTORYBOARDPERMISSIONDENIED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sTORYBOARDRENDERERROR_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              sTORYBOARDLOCKED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              sTORYBOARDSTATUSERROR_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              sTORYBOARDVERSIONERROR_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              sTORYBOARDSCENEERROR_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              sTORYBOARDGENERATIONFAILED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              sTORYBOARDOPERATIONDENIED_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sTORYBOARDNOTFOUND_ = "";
    /**
     * <pre>
     * 故事板不存在
     * </pre>
     *
     * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
     * @return The sTORYBOARDNOTFOUND.
     */
    public java.lang.String getSTORYBOARDNOTFOUND() {
      java.lang.Object ref = sTORYBOARDNOTFOUND_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDNOTFOUND_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板不存在
     * </pre>
     *
     * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
     * @return The bytes for sTORYBOARDNOTFOUND.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDNOTFOUNDBytes() {
      java.lang.Object ref = sTORYBOARDNOTFOUND_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDNOTFOUND_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板不存在
     * </pre>
     *
     * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
     * @param value The sTORYBOARDNOTFOUND to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDNOTFOUND(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDNOTFOUND_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板不存在
     * </pre>
     *
     * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDNOTFOUND() {
      sTORYBOARDNOTFOUND_ = getDefaultInstance().getSTORYBOARDNOTFOUND();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板不存在
     * </pre>
     *
     * <code>string STORYBOARD_NOT_FOUND = 1 [json_name = "STORYBOARDNOTFOUND"];</code>
     * @param value The bytes for sTORYBOARDNOTFOUND to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDNOTFOUNDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDNOTFOUND_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDALREADYEXISTS_ = "";
    /**
     * <pre>
     * 故事板已存在
     * </pre>
     *
     * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
     * @return The sTORYBOARDALREADYEXISTS.
     */
    public java.lang.String getSTORYBOARDALREADYEXISTS() {
      java.lang.Object ref = sTORYBOARDALREADYEXISTS_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDALREADYEXISTS_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板已存在
     * </pre>
     *
     * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
     * @return The bytes for sTORYBOARDALREADYEXISTS.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDALREADYEXISTSBytes() {
      java.lang.Object ref = sTORYBOARDALREADYEXISTS_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDALREADYEXISTS_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板已存在
     * </pre>
     *
     * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
     * @param value The sTORYBOARDALREADYEXISTS to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDALREADYEXISTS(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDALREADYEXISTS_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板已存在
     * </pre>
     *
     * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDALREADYEXISTS() {
      sTORYBOARDALREADYEXISTS_ = getDefaultInstance().getSTORYBOARDALREADYEXISTS();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板已存在
     * </pre>
     *
     * <code>string STORYBOARD_ALREADY_EXISTS = 2 [json_name = "STORYBOARDALREADYEXISTS"];</code>
     * @param value The bytes for sTORYBOARDALREADYEXISTS to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDALREADYEXISTSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDALREADYEXISTS_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDPERMISSIONDENIED_ = "";
    /**
     * <pre>
     * 故事板权限不足
     * </pre>
     *
     * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
     * @return The sTORYBOARDPERMISSIONDENIED.
     */
    public java.lang.String getSTORYBOARDPERMISSIONDENIED() {
      java.lang.Object ref = sTORYBOARDPERMISSIONDENIED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDPERMISSIONDENIED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板权限不足
     * </pre>
     *
     * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
     * @return The bytes for sTORYBOARDPERMISSIONDENIED.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDPERMISSIONDENIEDBytes() {
      java.lang.Object ref = sTORYBOARDPERMISSIONDENIED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDPERMISSIONDENIED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板权限不足
     * </pre>
     *
     * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
     * @param value The sTORYBOARDPERMISSIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDPERMISSIONDENIED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDPERMISSIONDENIED_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板权限不足
     * </pre>
     *
     * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDPERMISSIONDENIED() {
      sTORYBOARDPERMISSIONDENIED_ = getDefaultInstance().getSTORYBOARDPERMISSIONDENIED();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板权限不足
     * </pre>
     *
     * <code>string STORYBOARD_PERMISSION_DENIED = 3 [json_name = "STORYBOARDPERMISSIONDENIED"];</code>
     * @param value The bytes for sTORYBOARDPERMISSIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDPERMISSIONDENIEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDPERMISSIONDENIED_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDRENDERERROR_ = "";
    /**
     * <pre>
     * 故事板渲染错误
     * </pre>
     *
     * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
     * @return The sTORYBOARDRENDERERROR.
     */
    public java.lang.String getSTORYBOARDRENDERERROR() {
      java.lang.Object ref = sTORYBOARDRENDERERROR_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDRENDERERROR_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板渲染错误
     * </pre>
     *
     * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
     * @return The bytes for sTORYBOARDRENDERERROR.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDRENDERERRORBytes() {
      java.lang.Object ref = sTORYBOARDRENDERERROR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDRENDERERROR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板渲染错误
     * </pre>
     *
     * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
     * @param value The sTORYBOARDRENDERERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDRENDERERROR(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDRENDERERROR_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板渲染错误
     * </pre>
     *
     * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDRENDERERROR() {
      sTORYBOARDRENDERERROR_ = getDefaultInstance().getSTORYBOARDRENDERERROR();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板渲染错误
     * </pre>
     *
     * <code>string STORYBOARD_RENDER_ERROR = 4 [json_name = "STORYBOARDRENDERERROR"];</code>
     * @param value The bytes for sTORYBOARDRENDERERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDRENDERERRORBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDRENDERERROR_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDLOCKED_ = "";
    /**
     * <pre>
     * 故事板已锁定
     * </pre>
     *
     * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
     * @return The sTORYBOARDLOCKED.
     */
    public java.lang.String getSTORYBOARDLOCKED() {
      java.lang.Object ref = sTORYBOARDLOCKED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDLOCKED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板已锁定
     * </pre>
     *
     * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
     * @return The bytes for sTORYBOARDLOCKED.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDLOCKEDBytes() {
      java.lang.Object ref = sTORYBOARDLOCKED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDLOCKED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板已锁定
     * </pre>
     *
     * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
     * @param value The sTORYBOARDLOCKED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDLOCKED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDLOCKED_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板已锁定
     * </pre>
     *
     * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDLOCKED() {
      sTORYBOARDLOCKED_ = getDefaultInstance().getSTORYBOARDLOCKED();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板已锁定
     * </pre>
     *
     * <code>string STORYBOARD_LOCKED = 5 [json_name = "STORYBOARDLOCKED"];</code>
     * @param value The bytes for sTORYBOARDLOCKED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDLOCKEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDLOCKED_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDSTATUSERROR_ = "";
    /**
     * <pre>
     * 故事板状态错误
     * </pre>
     *
     * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
     * @return The sTORYBOARDSTATUSERROR.
     */
    public java.lang.String getSTORYBOARDSTATUSERROR() {
      java.lang.Object ref = sTORYBOARDSTATUSERROR_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDSTATUSERROR_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板状态错误
     * </pre>
     *
     * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
     * @return The bytes for sTORYBOARDSTATUSERROR.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDSTATUSERRORBytes() {
      java.lang.Object ref = sTORYBOARDSTATUSERROR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDSTATUSERROR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板状态错误
     * </pre>
     *
     * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
     * @param value The sTORYBOARDSTATUSERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDSTATUSERROR(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDSTATUSERROR_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板状态错误
     * </pre>
     *
     * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDSTATUSERROR() {
      sTORYBOARDSTATUSERROR_ = getDefaultInstance().getSTORYBOARDSTATUSERROR();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板状态错误
     * </pre>
     *
     * <code>string STORYBOARD_STATUS_ERROR = 6 [json_name = "STORYBOARDSTATUSERROR"];</code>
     * @param value The bytes for sTORYBOARDSTATUSERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDSTATUSERRORBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDSTATUSERROR_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDVERSIONERROR_ = "";
    /**
     * <pre>
     * 故事板版本错误
     * </pre>
     *
     * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
     * @return The sTORYBOARDVERSIONERROR.
     */
    public java.lang.String getSTORYBOARDVERSIONERROR() {
      java.lang.Object ref = sTORYBOARDVERSIONERROR_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDVERSIONERROR_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板版本错误
     * </pre>
     *
     * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
     * @return The bytes for sTORYBOARDVERSIONERROR.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDVERSIONERRORBytes() {
      java.lang.Object ref = sTORYBOARDVERSIONERROR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDVERSIONERROR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板版本错误
     * </pre>
     *
     * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
     * @param value The sTORYBOARDVERSIONERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDVERSIONERROR(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDVERSIONERROR_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板版本错误
     * </pre>
     *
     * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDVERSIONERROR() {
      sTORYBOARDVERSIONERROR_ = getDefaultInstance().getSTORYBOARDVERSIONERROR();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板版本错误
     * </pre>
     *
     * <code>string STORYBOARD_VERSION_ERROR = 7 [json_name = "STORYBOARDVERSIONERROR"];</code>
     * @param value The bytes for sTORYBOARDVERSIONERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDVERSIONERRORBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDVERSIONERROR_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDSCENEERROR_ = "";
    /**
     * <pre>
     * 故事板场景错误
     * </pre>
     *
     * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
     * @return The sTORYBOARDSCENEERROR.
     */
    public java.lang.String getSTORYBOARDSCENEERROR() {
      java.lang.Object ref = sTORYBOARDSCENEERROR_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDSCENEERROR_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板场景错误
     * </pre>
     *
     * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
     * @return The bytes for sTORYBOARDSCENEERROR.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDSCENEERRORBytes() {
      java.lang.Object ref = sTORYBOARDSCENEERROR_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDSCENEERROR_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板场景错误
     * </pre>
     *
     * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
     * @param value The sTORYBOARDSCENEERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDSCENEERROR(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDSCENEERROR_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板场景错误
     * </pre>
     *
     * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDSCENEERROR() {
      sTORYBOARDSCENEERROR_ = getDefaultInstance().getSTORYBOARDSCENEERROR();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板场景错误
     * </pre>
     *
     * <code>string STORYBOARD_SCENE_ERROR = 8 [json_name = "STORYBOARDSCENEERROR"];</code>
     * @param value The bytes for sTORYBOARDSCENEERROR to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDSCENEERRORBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDSCENEERROR_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDGENERATIONFAILED_ = "";
    /**
     * <pre>
     * 故事板生成失败
     * </pre>
     *
     * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
     * @return The sTORYBOARDGENERATIONFAILED.
     */
    public java.lang.String getSTORYBOARDGENERATIONFAILED() {
      java.lang.Object ref = sTORYBOARDGENERATIONFAILED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDGENERATIONFAILED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板生成失败
     * </pre>
     *
     * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
     * @return The bytes for sTORYBOARDGENERATIONFAILED.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDGENERATIONFAILEDBytes() {
      java.lang.Object ref = sTORYBOARDGENERATIONFAILED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDGENERATIONFAILED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板生成失败
     * </pre>
     *
     * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
     * @param value The sTORYBOARDGENERATIONFAILED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDGENERATIONFAILED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDGENERATIONFAILED_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板生成失败
     * </pre>
     *
     * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDGENERATIONFAILED() {
      sTORYBOARDGENERATIONFAILED_ = getDefaultInstance().getSTORYBOARDGENERATIONFAILED();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板生成失败
     * </pre>
     *
     * <code>string STORYBOARD_GENERATION_FAILED = 9 [json_name = "STORYBOARDGENERATIONFAILED"];</code>
     * @param value The bytes for sTORYBOARDGENERATIONFAILED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDGENERATIONFAILEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDGENERATIONFAILED_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object sTORYBOARDOPERATIONDENIED_ = "";
    /**
     * <pre>
     * 故事板操作被拒绝
     * </pre>
     *
     * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
     * @return The sTORYBOARDOPERATIONDENIED.
     */
    public java.lang.String getSTORYBOARDOPERATIONDENIED() {
      java.lang.Object ref = sTORYBOARDOPERATIONDENIED_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sTORYBOARDOPERATIONDENIED_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 故事板操作被拒绝
     * </pre>
     *
     * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
     * @return The bytes for sTORYBOARDOPERATIONDENIED.
     */
    public com.google.protobuf.ByteString
        getSTORYBOARDOPERATIONDENIEDBytes() {
      java.lang.Object ref = sTORYBOARDOPERATIONDENIED_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sTORYBOARDOPERATIONDENIED_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 故事板操作被拒绝
     * </pre>
     *
     * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
     * @param value The sTORYBOARDOPERATIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDOPERATIONDENIED(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sTORYBOARDOPERATIONDENIED_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板操作被拒绝
     * </pre>
     *
     * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSTORYBOARDOPERATIONDENIED() {
      sTORYBOARDOPERATIONDENIED_ = getDefaultInstance().getSTORYBOARDOPERATIONDENIED();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 故事板操作被拒绝
     * </pre>
     *
     * <code>string STORYBOARD_OPERATION_DENIED = 10 [json_name = "STORYBOARDOPERATIONDENIED"];</code>
     * @param value The bytes for sTORYBOARDOPERATIONDENIED to set.
     * @return This builder for chaining.
     */
    public Builder setSTORYBOARDOPERATIONDENIEDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sTORYBOARDOPERATIONDENIED_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.StoryboardErrorMessages)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.StoryboardErrorMessages)
  private static final com.rankquantity.voyager.api.StoryboardErrorMessages DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.StoryboardErrorMessages();
  }

  public static com.rankquantity.voyager.api.StoryboardErrorMessages getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StoryboardErrorMessages>
      PARSER = new com.google.protobuf.AbstractParser<StoryboardErrorMessages>() {
    @java.lang.Override
    public StoryboardErrorMessages parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StoryboardErrorMessages> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StoryboardErrorMessages> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.StoryboardErrorMessages getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

