// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface StoryboardDraftDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.StoryboardDraftDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 草稿ID
   * </pre>
   *
   * <code>int64 draft_id = 1 [json_name = "draftId"];</code>
   * @return The draftId.
   */
  long getDraftId();

  /**
   * <pre>
   * 故事ID
   * </pre>
   *
   * <code>int64 story_id = 2 [json_name = "storyId"];</code>
   * @return The storyId.
   */
  long getStoryId();

  /**
   * <pre>
   * 故事板ID
   * </pre>
   *
   * <code>int64 storyboard_id = 3 [json_name = "storyboardId"];</code>
   * @return The storyboardId.
   */
  long getStoryboardId();

  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 4 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 标题
   * </pre>
   *
   * <code>string title = 4 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>string content = 5 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>string content = 5 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 背景
   * </pre>
   *
   * <code>string background = 6 [json_name = "background"];</code>
   * @return The background.
   */
  java.lang.String getBackground();
  /**
   * <pre>
   * 背景
   * </pre>
   *
   * <code>string background = 6 [json_name = "background"];</code>
   * @return The bytes for background.
   */
  com.google.protobuf.ByteString
      getBackgroundBytes();

  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryRole roles = 7 [json_name = "roles"];</code>
   */
  java.util.List<com.rankquantity.voyager.api.StoryRole> 
      getRolesList();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryRole roles = 7 [json_name = "roles"];</code>
   */
  com.rankquantity.voyager.api.StoryRole getRoles(int index);
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryRole roles = 7 [json_name = "roles"];</code>
   */
  int getRolesCount();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryRole roles = 7 [json_name = "roles"];</code>
   */
  java.util.List<? extends com.rankquantity.voyager.api.StoryRoleOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <pre>
   * 角色列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryRole roles = 7 [json_name = "roles"];</code>
   */
  com.rankquantity.voyager.api.StoryRoleOrBuilder getRolesOrBuilder(
      int index);

  /**
   * <pre>
   * 场景列表
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardSences sences = 8 [json_name = "sences"];</code>
   * @return Whether the sences field is set.
   */
  boolean hasSences();
  /**
   * <pre>
   * 场景列表
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardSences sences = 8 [json_name = "sences"];</code>
   * @return The sences.
   */
  com.rankquantity.voyager.api.StoryBoardSences getSences();
  /**
   * <pre>
   * 场景列表
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardSences sences = 8 [json_name = "sences"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardSencesOrBuilder getSencesOrBuilder();

  /**
   * <pre>
   * 故事板参数
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 9 [json_name = "params"];</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <pre>
   * 故事板参数
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 9 [json_name = "params"];</code>
   * @return The params.
   */
  com.rankquantity.voyager.api.StoryBoardParams getParams();
  /**
   * <pre>
   * 故事板参数
   * </pre>
   *
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 9 [json_name = "params"];</code>
   */
  com.rankquantity.voyager.api.StoryBoardParamsOrBuilder getParamsOrBuilder();

  /**
   * <pre>
   * 创建时间戳
   * </pre>
   *
   * <code>int64 created_at = 10 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * 更新时间戳
   * </pre>
   *
   * <code>int64 updated_at = 11 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();

  /**
   * <pre>
   * 版本号
   * </pre>
   *
   * <code>int64 version = 12 [json_name = "version"];</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 user_id = 13 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();
}
