// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface TokenConsumptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.TokenConsumption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#47; Token消耗数量
   * </pre>
   *
   * <code>int64 token_count = 1 [json_name = "tokenCount"];</code>
   * @return The tokenCount.
   */
  long getTokenCount();

  /**
   * <pre>
   * &#47; Token来源类型
   * </pre>
   *
   * <code>.rankquantity.voyager.api.TokenSourceType source_type = 2 [json_name = "sourceType"];</code>
   * @return The enum numeric value on the wire for sourceType.
   */
  int getSourceTypeValue();
  /**
   * <pre>
   * &#47; Token来源类型
   * </pre>
   *
   * <code>.rankquantity.voyager.api.TokenSourceType source_type = 2 [json_name = "sourceType"];</code>
   * @return The sourceType.
   */
  com.rankquantity.voyager.api.TokenSourceType getSourceType();

  /**
   * <pre>
   * &#47; 来源ID（个人用户ID或机构ID）
   * </pre>
   *
   * <code>int64 source_id = 3 [json_name = "sourceId"];</code>
   * @return The sourceId.
   */
  long getSourceId();

  /**
   * <pre>
   * &#47; 消耗时间戳
   * </pre>
   *
   * <code>int64 consumed_at = 4 [json_name = "consumedAt"];</code>
   * @return The consumedAt.
   */
  long getConsumedAt();

  /**
   * <pre>
   * &#47; 消耗用途描述
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The purpose.
   */
  java.lang.String getPurpose();
  /**
   * <pre>
   * &#47; 消耗用途描述
   * </pre>
   *
   * <code>string purpose = 5 [json_name = "purpose"];</code>
   * @return The bytes for purpose.
   */
  com.google.protobuf.ByteString
      getPurposeBytes();
}
