// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface TrendingStoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.TrendingStoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>int64 end = 2 [json_name = "end"];</code>
   * @return The end.
   */
  long getEnd();

  /**
   * <code>int64 page_size = 3 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  long getPageSize();

  /**
   * <code>int64 page_number = 4 [json_name = "pageNumber"];</code>
   * @return The pageNumber.
   */
  long getPageNumber();
}
