// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

/**
 * Protobuf type {@code rankquantity.voyager.api.UpdateStoryboardRequest}
 */
@com.google.protobuf.Generated
public final class UpdateStoryboardRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:rankquantity.voyager.api.UpdateStoryboardRequest)
    UpdateStoryboardRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      UpdateStoryboardRequest.class.getName());
  }
  // Use UpdateStoryboardRequest.newBuilder() to construct.
  private UpdateStoryboardRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateStoryboardRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_UpdateStoryboardRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_UpdateStoryboardRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rankquantity.voyager.api.UpdateStoryboardRequest.class, com.rankquantity.voyager.api.UpdateStoryboardRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BOARD_ID_FIELD_NUMBER = 1;
  private long boardId_ = 0L;
  /**
   * <code>int64 board_id = 1 [json_name = "boardId"];</code>
   * @return The boardId.
   */
  @java.lang.Override
  public long getBoardId() {
    return boardId_;
  }

  public static final int STORY_ID_FIELD_NUMBER = 2;
  private long storyId_ = 0L;
  /**
   * <code>int64 story_id = 2 [json_name = "storyId"];</code>
   * @return The storyId.
   */
  @java.lang.Override
  public long getStoryId() {
    return storyId_;
  }

  public static final int USER_ID_FIELD_NUMBER = 3;
  private long userId_ = 0L;
  /**
   * <code>int64 user_id = 3 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int PARAMS_FIELD_NUMBER = 4;
  private com.rankquantity.voyager.api.StoryBoardParams params_;
  /**
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
   * @return Whether the params field is set.
   */
  @java.lang.Override
  public boolean hasParams() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
   * @return The params.
   */
  @java.lang.Override
  public com.rankquantity.voyager.api.StoryBoardParams getParams() {
    return params_ == null ? com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance() : params_;
  }
  /**
   * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
   */
  @java.lang.Override
  public com.rankquantity.voyager.api.StoryBoardParamsOrBuilder getParamsOrBuilder() {
    return params_ == null ? com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance() : params_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (boardId_ != 0L) {
      output.writeInt64(1, boardId_);
    }
    if (storyId_ != 0L) {
      output.writeInt64(2, storyId_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getParams());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (boardId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, boardId_);
    }
    if (storyId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, storyId_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getParams());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rankquantity.voyager.api.UpdateStoryboardRequest)) {
      return super.equals(obj);
    }
    com.rankquantity.voyager.api.UpdateStoryboardRequest other = (com.rankquantity.voyager.api.UpdateStoryboardRequest) obj;

    if (getBoardId()
        != other.getBoardId()) return false;
    if (getStoryId()
        != other.getStoryId()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (hasParams() != other.hasParams()) return false;
    if (hasParams()) {
      if (!getParams()
          .equals(other.getParams())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOARD_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBoardId());
    hash = (37 * hash) + STORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStoryId());
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    if (hasParams()) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.rankquantity.voyager.api.UpdateStoryboardRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rankquantity.voyager.api.UpdateStoryboardRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rankquantity.voyager.api.UpdateStoryboardRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rankquantity.voyager.api.UpdateStoryboardRequest)
      com.rankquantity.voyager.api.UpdateStoryboardRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_UpdateStoryboardRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_UpdateStoryboardRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rankquantity.voyager.api.UpdateStoryboardRequest.class, com.rankquantity.voyager.api.UpdateStoryboardRequest.Builder.class);
    }

    // Construct using com.rankquantity.voyager.api.UpdateStoryboardRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetParamsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      boardId_ = 0L;
      storyId_ = 0L;
      userId_ = 0L;
      params_ = null;
      if (paramsBuilder_ != null) {
        paramsBuilder_.dispose();
        paramsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rankquantity.voyager.api.StoryProto.internal_static_rankquantity_voyager_api_UpdateStoryboardRequest_descriptor;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.UpdateStoryboardRequest getDefaultInstanceForType() {
      return com.rankquantity.voyager.api.UpdateStoryboardRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.UpdateStoryboardRequest build() {
      com.rankquantity.voyager.api.UpdateStoryboardRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rankquantity.voyager.api.UpdateStoryboardRequest buildPartial() {
      com.rankquantity.voyager.api.UpdateStoryboardRequest result = new com.rankquantity.voyager.api.UpdateStoryboardRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.rankquantity.voyager.api.UpdateStoryboardRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.boardId_ = boardId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.storyId_ = storyId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userId_ = userId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.params_ = paramsBuilder_ == null
            ? params_
            : paramsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rankquantity.voyager.api.UpdateStoryboardRequest) {
        return mergeFrom((com.rankquantity.voyager.api.UpdateStoryboardRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rankquantity.voyager.api.UpdateStoryboardRequest other) {
      if (other == com.rankquantity.voyager.api.UpdateStoryboardRequest.getDefaultInstance()) return this;
      if (other.getBoardId() != 0L) {
        setBoardId(other.getBoardId());
      }
      if (other.getStoryId() != 0L) {
        setStoryId(other.getStoryId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.hasParams()) {
        mergeParams(other.getParams());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              boardId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              storyId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  internalGetParamsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long boardId_ ;
    /**
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @return The boardId.
     */
    @java.lang.Override
    public long getBoardId() {
      return boardId_;
    }
    /**
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @param value The boardId to set.
     * @return This builder for chaining.
     */
    public Builder setBoardId(long value) {

      boardId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 board_id = 1 [json_name = "boardId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoardId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      boardId_ = 0L;
      onChanged();
      return this;
    }

    private long storyId_ ;
    /**
     * <code>int64 story_id = 2 [json_name = "storyId"];</code>
     * @return The storyId.
     */
    @java.lang.Override
    public long getStoryId() {
      return storyId_;
    }
    /**
     * <code>int64 story_id = 2 [json_name = "storyId"];</code>
     * @param value The storyId to set.
     * @return This builder for chaining.
     */
    public Builder setStoryId(long value) {

      storyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 story_id = 2 [json_name = "storyId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStoryId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      storyId_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 user_id = 3 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 3 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 3 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private com.rankquantity.voyager.api.StoryBoardParams params_;
    private com.google.protobuf.SingleFieldBuilder<
        com.rankquantity.voyager.api.StoryBoardParams, com.rankquantity.voyager.api.StoryBoardParams.Builder, com.rankquantity.voyager.api.StoryBoardParamsOrBuilder> paramsBuilder_;
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     * @return Whether the params field is set.
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     * @return The params.
     */
    public com.rankquantity.voyager.api.StoryBoardParams getParams() {
      if (paramsBuilder_ == null) {
        return params_ == null ? com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance() : params_;
      } else {
        return paramsBuilder_.getMessage();
      }
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public Builder setParams(com.rankquantity.voyager.api.StoryBoardParams value) {
      if (paramsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        params_ = value;
      } else {
        paramsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public Builder setParams(
        com.rankquantity.voyager.api.StoryBoardParams.Builder builderForValue) {
      if (paramsBuilder_ == null) {
        params_ = builderForValue.build();
      } else {
        paramsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public Builder mergeParams(com.rankquantity.voyager.api.StoryBoardParams value) {
      if (paramsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          params_ != null &&
          params_ != com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance()) {
          getParamsBuilder().mergeFrom(value);
        } else {
          params_ = value;
        }
      } else {
        paramsBuilder_.mergeFrom(value);
      }
      if (params_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public Builder clearParams() {
      bitField0_ = (bitField0_ & ~0x00000008);
      params_ = null;
      if (paramsBuilder_ != null) {
        paramsBuilder_.dispose();
        paramsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public com.rankquantity.voyager.api.StoryBoardParams.Builder getParamsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetParamsFieldBuilder().getBuilder();
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    public com.rankquantity.voyager.api.StoryBoardParamsOrBuilder getParamsOrBuilder() {
      if (paramsBuilder_ != null) {
        return paramsBuilder_.getMessageOrBuilder();
      } else {
        return params_ == null ?
            com.rankquantity.voyager.api.StoryBoardParams.getDefaultInstance() : params_;
      }
    }
    /**
     * <code>.rankquantity.voyager.api.StoryBoardParams params = 4 [json_name = "params"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.rankquantity.voyager.api.StoryBoardParams, com.rankquantity.voyager.api.StoryBoardParams.Builder, com.rankquantity.voyager.api.StoryBoardParamsOrBuilder> 
        internalGetParamsFieldBuilder() {
      if (paramsBuilder_ == null) {
        paramsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.rankquantity.voyager.api.StoryBoardParams, com.rankquantity.voyager.api.StoryBoardParams.Builder, com.rankquantity.voyager.api.StoryBoardParamsOrBuilder>(
                getParams(),
                getParentForChildren(),
                isClean());
        params_ = null;
      }
      return paramsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:rankquantity.voyager.api.UpdateStoryboardRequest)
  }

  // @@protoc_insertion_point(class_scope:rankquantity.voyager.api.UpdateStoryboardRequest)
  private static final com.rankquantity.voyager.api.UpdateStoryboardRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rankquantity.voyager.api.UpdateStoryboardRequest();
  }

  public static com.rankquantity.voyager.api.UpdateStoryboardRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateStoryboardRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateStoryboardRequest>() {
    @java.lang.Override
    public UpdateStoryboardRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateStoryboardRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateStoryboardRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rankquantity.voyager.api.UpdateStoryboardRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

