// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface UpdateStoryRoleAvatorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.UpdateStoryRoleAvatorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#47; 角色ID，必须大于0
   * </pre>
   *
   * <code>int64 role_id = 1 [json_name = "roleId", (.validate.rules) = { ... }</code>
   * @return The roleId.
   */
  long getRoleId();

  /**
   * <pre>
   * &#47; 头像URL，必填
   * </pre>
   *
   * <code>string avator = 2 [json_name = "avator", (.validate.rules) = { ... }</code>
   * @return The avator.
   */
  java.lang.String getAvator();
  /**
   * <pre>
   * &#47; 头像URL，必填
   * </pre>
   *
   * <code>string avator = 2 [json_name = "avator", (.validate.rules) = { ... }</code>
   * @return The bytes for avator.
   */
  com.google.protobuf.ByteString
      getAvatorBytes();

  /**
   * <pre>
   * &#47; 用户ID，必须大于0
   * </pre>
   *
   * <code>int64 user_id = 3 [json_name = "userId", (.validate.rules) = { ... }</code>
   * @return The userId.
   */
  long getUserId();
}
