// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface UserStoryboardDraftlistResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.UserStoryboardDraftlistResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应码
   * </pre>
   *
   * <code>.rankquantity.voyager.api.ResponseCode code = 1 [json_name = "code"];</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   * 响应码
   * </pre>
   *
   * <code>.rankquantity.voyager.api.ResponseCode code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  com.rankquantity.voyager.api.ResponseCode getCode();

  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 草稿列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryboardDraftItem drafts = 3 [json_name = "drafts"];</code>
   */
  java.util.List<com.rankquantity.voyager.api.StoryboardDraftItem> 
      getDraftsList();
  /**
   * <pre>
   * 草稿列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryboardDraftItem drafts = 3 [json_name = "drafts"];</code>
   */
  com.rankquantity.voyager.api.StoryboardDraftItem getDrafts(int index);
  /**
   * <pre>
   * 草稿列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryboardDraftItem drafts = 3 [json_name = "drafts"];</code>
   */
  int getDraftsCount();
  /**
   * <pre>
   * 草稿列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryboardDraftItem drafts = 3 [json_name = "drafts"];</code>
   */
  java.util.List<? extends com.rankquantity.voyager.api.StoryboardDraftItemOrBuilder> 
      getDraftsOrBuilderList();
  /**
   * <pre>
   * 草稿列表
   * </pre>
   *
   * <code>repeated .rankquantity.voyager.api.StoryboardDraftItem drafts = 3 [json_name = "drafts"];</code>
   */
  com.rankquantity.voyager.api.StoryboardDraftItemOrBuilder getDraftsOrBuilder(
      int index);

  /**
   * <pre>
   * 草稿总数
   * </pre>
   *
   * <code>int64 total = 4 [json_name = "total"];</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <pre>
   * 是否有更多
   * </pre>
   *
   * <code>bool have_more = 5 [json_name = "haveMore"];</code>
   * @return The haveMore.
   */
  boolean getHaveMore();
}
