// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface UserPrivateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.UserPrivate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 connect_type = 1 [json_name = "connectType"];</code>
   * @return The connectType.
   */
  long getConnectType();

  /**
   * <code>int64 Ctime = 10 [json_name = "Ctime"];</code>
   * @return The ctime.
   */
  long getCtime();

  /**
   * <code>int64 Mtime = 11 [json_name = "Mtime"];</code>
   * @return The mtime.
   */
  long getMtime();
}
