// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: item.proto
// Protobuf Java Version: 4.32.1

package com.rankquantity.voyager.api;

@com.google.protobuf.Generated
public interface VoiceDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rankquantity.voyager.api.VoiceDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resource_url = 1 [json_name = "resourceUrl"];</code>
   * @return The resourceUrl.
   */
  java.lang.String getResourceUrl();
  /**
   * <code>string resource_url = 1 [json_name = "resourceUrl"];</code>
   * @return The bytes for resourceUrl.
   */
  com.google.protobuf.ByteString
      getResourceUrlBytes();

  /**
   * <code>int64 size = 2 [json_name = "size"];</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>int64 time_length = 3 [json_name = "timeLength"];</code>
   * @return The timeLength.
   */
  long getTimeLength();

  /**
   * <code>int64 Ctime = 9 [json_name = "Ctime"];</code>
   * @return The ctime.
   */
  long getCtime();

  /**
   * <code>int64 Mtime = 10 [json_name = "Mtime"];</code>
   * @return The mtime.
   */
  long getMtime();
}
